// apps/eden/ts/src/components/dialogs/DeleteDialog.tsx
interface DeleteDialogProps {
  target: { kind: 'entry' | 'folder'; id: string; title: string } | null;
  onCancel: () => void;
  onConfirm: (target: { kind: 'entry' | 'folder'; id: string; title: string }) => void;
}

export default function DeleteDialog({ target, onCancel, onConfirm }: DeleteDialogProps) {
  if (!target) {
    return null
  }

  return (
    <div className="dialog-backdrop" data-testid="delete-dialog" onClick={onCancel}>
      <div className="dialog-card" onClick={(event) => event.stopPropagation()}>
        <div className="dialog-header">
          <div>
            <p className="dialog-kicker">Удаление</p>
            <h2 className="dialog-title">
              {target.kind === 'entry' ? 'Удалить заметку?' : 'Удалить папку?'}
            </h2>
          </div>
          <button className="dialog-close-btn" onClick={onCancel} type="button">
            ×
          </button>
        </div>
        <div className="dialog-field">
          <p>
            Вы уверены, что хотите удалить {target.kind === 'entry' ? 'заметку' : 'папку'} <strong>{target.title}</strong>?
            {target.kind === 'folder' && ' Удаление доступно только для пустой папки без вложенных папок и заметок.'}
          </p>
        </div>
        <div className="dialog-actions">
          <button className="dialog-secondary-btn" data-testid="delete-dialog-cancel" onClick={onCancel} type="button">
            Отмена
          </button>
          <button
            className="dialog-primary-btn dialog-primary-btn-danger"
            data-testid="delete-dialog-submit"
            onClick={() => onConfirm(target)}
            type="button"
          >
            Удалить
          </button>
        </div>
      </div>
    </div>
  )
}

// extensions/eden/src/components/dialogs/DeleteDialog.vue
<template>
  <Modal
    :open="!!target"
    :title="target?.kind === 'entry' ? 'Удалить заметку?' : 'Удалить папку?'"
    width="min(100%, 340px)"
    data-testid="delete-dialog"
    @close="emit('cancel')"
  >
    <p>
      Вы уверены, что хотите удалить
      {{ target?.kind === "entry" ? "заметку" : "папку" }}
      <strong>{{ target?.title }}</strong
      >?
      <template v-if="target?.kind === 'folder'">
        Удаление доступно только для пустой папки без вложенных папок и заметок.
      </template>
    </p>
    <template #footer>
      <button
        class="dialog-secondary-btn"
        data-testid="delete-dialog-cancel"
        type="button"
        @click="emit('cancel')"
      >
        Отмена
      </button>
      <button
        class="dialog-primary-btn dialog-primary-btn-danger"
        data-testid="delete-dialog-submit"
        type="button"
        @click="target && emit('confirm', target)"
      >
        Удалить
      </button>
    </template>
  </Modal>
</template>

<script setup vapor lang="ts">
import { Modal } from "@kosmos/visuals";

export interface DeleteDialogTarget {
  kind: "entry" | "folder";
  id: string;
  title: string;
}

defineProps<{
  target: DeleteDialogTarget | null;
}>();

const emit = defineEmits<{
  cancel: [];
  confirm: [target: DeleteDialogTarget];
}>();
</script>
