// apps/eden/ts/src/components/SearchOverlay.vue
<template>
  <div
    v-if="isOpen"
    class="search-overlay-backdrop"
    role="dialog"
    aria-modal="true"
    @click.self="emit('close')"
  >
    <div class="search-overlay" @keydown="handleKeyDown">
      <div class="search-overlay-input-wrap">
        <svg
          class="search-overlay-icon"
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <circle cx="11" cy="11" r="8" />
          <line x1="21" y1="21" x2="16.65" y2="16.65" />
        </svg>
        <input
          ref="inputRef"
          type="text"
          class="search-overlay-input"
          placeholder="Поиск..."
          :value="query"
          autofocus
          @input="emit('queryChange', ($event.target as HTMLInputElement).value)"
        />
        <button v-if="query" class="search-overlay-clear-btn" type="button" @click="emit('close')">
          <svg
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>
      </div>
      <div class="search-overlay-results">
        <template v-if="query.trim()">
          <template v-if="results.length > 0">
            <div
              v-for="(result, index) in results"
              :key="`${result.entryId}-${index}`"
              class="search-overlay-result-item"
              :class="{ 'is-selected': selectedIndex === index }"
              @click="void emit('resultSelect', result.entryId)"
              @mouseenter="selectedIndex = index"
            >
              <div class="entry-title">
                {{ entries.find((e) => e.id === result.entryId)?.title || "Без названия" }}
              </div>
              <div class="search-result-text">{{ result.text }}</div>
            </div>
          </template>
          <div v-else class="search-overlay-empty">Ничего не найдено</div>
        </template>
        <div v-else class="search-overlay-empty">Начните вводить для поиска</div>
      </div>
      <div class="search-overlay-footer">
        <div class="search-overlay-hint">
          <kbd>↑</kbd><kbd>↓</kbd>
          <span>навигация</span>
        </div>
        <div class="search-overlay-hint">
          <kbd>Enter</kbd>
          <span>открыть</span>
        </div>
        <div class="search-overlay-hint">
          <kbd>Esc</kbd>
          <span>закрыть</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup vapor lang="ts">
import { ref, watch } from "vue";
import "./SearchOverlay.css";

const props = defineProps<{
  isOpen: boolean;
  query: string;
  results: SearchResult[];
  entries: Entry[];
}>();

const emit = defineEmits<{
  queryChange: [value: string];
  close: [];
  resultSelect: [entryId: string];
}>();

const inputRef = ref<HTMLInputElement | null>(null);
const selectedIndex = ref(0);

watch(
  () => props.isOpen,
  (open) => {
    if (open) {
      selectedIndex.value = 0;
      setTimeout(() => inputRef.value?.focus(), 0);
    }
  },
);

watch(
  () => props.results,
  () => {
    selectedIndex.value = 0;
  },
);

function handleKeyDown(event: KeyboardEvent) {
  switch (event.key) {
    case "ArrowDown":
      event.preventDefault();
      selectedIndex.value = Math.min(selectedIndex.value + 1, props.results.length - 1);
      break;
    case "ArrowUp":
      event.preventDefault();
      selectedIndex.value = Math.max(selectedIndex.value - 1, 0);
      break;
    case "Enter":
      event.preventDefault();
      if (props.results[selectedIndex.value]) {
        emit("resultSelect", props.results[selectedIndex.value].entryId);
      }
      break;
    case "Escape":
      event.preventDefault();
      emit("close");
      break;
  }
}
</script>

// apps/eden/ts/src/components/SearchOverlay.tsx
import './SearchOverlay.css'
import { useCallback, useEffect, useRef, useState } from 'react'

interface SearchOverlayProps {
  isOpen: boolean
  query: string
  results: SearchResult[]
  entries: Entry[]
  onQueryChange: (value: string) => void
  onClose: () => void
  onResultSelect: (entryId: string) => Promise<void>
}

export default function SearchOverlay({
  isOpen,
  query,
  results,
  entries,
  onQueryChange,
  onClose,
  onResultSelect,
}: SearchOverlayProps) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [selectedIndex, setSelectedIndex] = useState(0)

  useEffect(() => {
    if (isOpen) {
      setSelectedIndex(0)
      setTimeout(() => {
        inputRef.current?.focus()
      }, 0)
    }
  }, [isOpen])

  useEffect(() => {
    setSelectedIndex(0)
  }, [results])

  const handleKeyDown = useCallback((event: React.KeyboardEvent) => {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault()
        setSelectedIndex(prev => Math.min(prev + 1, results.length - 1))
        break
      case 'ArrowUp':
        event.preventDefault()
        setSelectedIndex(prev => Math.max(prev - 1, 0))
        break
      case 'Enter':
        event.preventDefault()
        if (results[selectedIndex]) {
          void onResultSelect(results[selectedIndex].entryId)
        }
        break
      case 'Escape':
        event.preventDefault()
        onClose()
        break
    }
  }, [results, selectedIndex, onResultSelect, onClose])

  const handleBackdropClick = useCallback((event: React.MouseEvent) => {
    if (event.target === event.currentTarget) {
      onClose()
    }
  }, [onClose])

  if (!isOpen) return null

  return (
    <div 
      className="search-overlay-backdrop" 
      onClick={handleBackdropClick}
      role="dialog"
      aria-modal="true"
    >
      <div className="search-overlay" onKeyDown={handleKeyDown}>
        <div className="search-overlay-input-wrap">
          <svg className="search-overlay-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="11" cy="11" r="8"></circle>
            <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
          </svg>
          <input
            ref={inputRef}
            type="text"
            className="search-overlay-input"
            placeholder="Поиск..."
            value={query}
            onChange={(event) => onQueryChange(event.target.value)}
            autoFocus
          />
          {query && (
            <button className="search-overlay-clear-btn" onClick={onClose}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18"></line>
                <line x1="6" y1="6" x2="18" y2="18"></line>
              </svg>
            </button>
          )}
        </div>
        <div className="search-overlay-results">
          {query.trim() ? (
            results.length > 0 ? (
              results.map((result, index) => {
                const entry = entries.find(e => e.id === result.entryId)
                return (
                  <div
                    key={`${result.entryId}-${index}`}
                    className={`search-overlay-result-item ${selectedIndex === index ? 'is-selected' : ''}`}
                    onClick={() => void onResultSelect(result.entryId)}
                    onMouseEnter={() => setSelectedIndex(index)}
                  >
                    <div className="entry-title">{entry?.title || 'Без названия'}</div>
                    <div className="search-result-text">{result.text}</div>
                  </div>
                )
              })
            ) : (
              <div className="search-overlay-empty">Ничего не найдено</div>
            )
          ) : (
            <div className="search-overlay-empty">Начните вводить для поиска</div>
          )}
        </div>
        <div className="search-overlay-footer">
          <div className="search-overlay-hint">
            <kbd>↑</kbd><kbd>↓</kbd>
            <span>навигация</span>
          </div>
          <div className="search-overlay-hint">
            <kbd>Enter</kbd>
            <span>открыть</span>
          </div>
          <div className="search-overlay-hint">
            <kbd>Esc</kbd>
            <span>закрыть</span>
          </div>
        </div>
      </div>
    </div>
  )
}
