// extensions/eden/src/components/dialogs/FolderDialog.vue
<template>
  <div v-if="isOpen" class="dialog-backdrop" data-testid="folder-dialog" @click="emit('close')">
    <div class="dialog-card" @click.stop>
      <div class="dialog-header">
        <div>
          <p class="dialog-kicker">Новая папка</p>
          <h2 class="dialog-title">Создать папку</h2>
        </div>
        <button class="dialog-close-btn" type="button" @click="emit('close')">×</button>
      </div>
      <label class="dialog-field">
        <span>Название папки</span>
        <input
          ref="inputRef"
          class="dialog-input"
          type="text"
          placeholder="Например, Проекты"
          :value="name"
          @input="emit('nameChange', ($event.target as HTMLInputElement).value)"
        />
      </label>
      <div v-if="error" class="dialog-error">{{ error }}</div>
      <div class="dialog-actions">
        <button
          class="dialog-secondary-btn"
          data-testid="folder-dialog-cancel"
          type="button"
          @click="emit('close')"
        >
          Отмена
        </button>
        <button
          class="dialog-primary-btn"
          data-testid="folder-dialog-submit"
          type="button"
          title="Создать папку"
          :disabled="isCreating"
          @click="emit('submit')"
        >
          {{ isCreating ? "Создание..." : "Создать папку" }}
        </button>
      </div>
    </div>
  </div>
</template>

<script setup vapor lang="ts">
import { useTemplateRef } from "vue";

defineProps<{
  isOpen: boolean;
  isCreating: boolean;
  name: string;
  error: string | null;
}>();

const emit = defineEmits<{
  nameChange: [value: string];
  close: [];
  submit: [];
}>();

const inputRef = useTemplateRef<HTMLInputElement>("inputRef");

defineExpose({ inputRef });
</script>

// apps/eden/ts/src/components/dialogs/FolderDialog.tsx
import { RefObject } from 'react'

interface FolderDialogProps {
  isOpen: boolean;
  isCreating: boolean;
  name: string;
  error: string | null;
  inputRef: RefObject<HTMLInputElement>;
  onNameChange: (value: string) => void;
  onClose: () => void;
  onSubmit: () => void;
}

export default function FolderDialog({
  isOpen,
  isCreating,
  name,
  error,
  inputRef,
  onNameChange,
  onClose,
  onSubmit,
}: FolderDialogProps) {
  if (!isOpen) {
    return null
  }

  return (
    <div className="dialog-backdrop" data-testid="folder-dialog" onClick={onClose}>
      <div className="dialog-card" onClick={(event) => event.stopPropagation()}>
        <div className="dialog-header">
          <div>
            <p className="dialog-kicker">Новая папка</p>
            <h2 className="dialog-title">Создать папку</h2>
          </div>
          <button className="dialog-close-btn" onClick={onClose} type="button">
            ×
          </button>
        </div>
        <label className="dialog-field">
          <span>Название папки</span>
          <input
            ref={inputRef}
            className="dialog-input"
            value={name}
            onChange={(event) => onNameChange(event.target.value)}
            placeholder="Например, Проекты"
            type="text"
          />
        </label>
        {error && <div className="dialog-error">{error}</div>}
        <div className="dialog-actions">
          <button className="dialog-secondary-btn" data-testid="folder-dialog-cancel" onClick={onClose} type="button">
            Отмена
          </button>
          <button className="dialog-primary-btn" data-testid="folder-dialog-submit" disabled={isCreating} onClick={onSubmit} type="button" title="Создать папку">
            {isCreating ? 'Создание...' : 'Создать папку'}
          </button>
        </div>
      </div>
    </div>
  )
}
