// apps/delphi/ts/src/pages/LogbookPage.vue
<script setup lang="ts">
import { computed } from "vue";
import { Book } from "lucide-vue-next";
import { SmartList } from "@/types/task";
import { useTodoStore } from "@/store/todos";
import { storeToRefs } from "pinia";
import { filterTodos } from "@/services/filters/todoFilterService";
import TodoRow from "@kepler/visuals/components/TodoRow.vue";

const store = useTodoStore();
const { todos } = storeToRefs(store);
const filtered = computed(() => filterTodos(SmartList.Logbook, todos.value));
</script>

<template>
  <div class="flex min-h-0 w-full min-w-0 flex-1 flex-col">
    <div class="flex items-center gap-2.5 px-7 pb-3 pt-6">
      <Book :size="24" class="text-green-500" />
      <h1 class="text-2xl font-bold text-(--foreground) select-none">Журнал</h1>
      <span
        v-if="filtered.length > 0"
        class="text-sm text-(--muted-foreground)"
      >
        {{ filtered.length }}
      </span>
    </div>

    <div class="scrollbar-gutter flex-1 overflow-y-auto">
      <div class="pb-20 pt-1">
        <div
          v-if="filtered.length === 0"
          class="px-7 py-10 text-center text-sm text-(--muted-foreground)/60"
        >
          Завершённых задач нет
        </div>
        <div v-else class="flex flex-col">
          <TodoRow
            v-for="todo in filtered"
            :key="todo.id"
            :todo="todo"
            @complete="store.incompleteTodo(todo.id)"
          />
        </div>
      </div>
    </div>
  </div>
</template>

// apps/delphi/ts/src/pages/LogbookPage.tsx
import { Book } from "lucide-react";
import useSmartList from "@/hooks/useSmartList";
import { SmartList } from "@/types/task";
import TodoRow from "@/components/TodoRow";
import useTodoStore from "@/store/todos";

export default function LogbookPage() {
  const { filtered } = useSmartList(SmartList.Logbook);
  const incompleteTodo = useTodoStore((s) => s.incompleteTodo);

  return (
    <div className="flex w-full min-w-0 flex-col">
      <div className="flex items-center gap-2.5 px-7 pb-3 pt-6">
        <Book size={24} className="text-green-500" />
        <h1 className="text-2xl font-bold text-(--foreground) select-none">
          Журнал
        </h1>
        {filtered.length > 0 && (
          <span className="text-sm text-(--muted-foreground)">
            {filtered.length}
          </span>
        )}
      </div>

      <div className="scrollbar-gutter flex-1 overflow-y-auto">
        <div className="pb-20 pt-1">
          {filtered.length === 0 ? (
            <div className="px-7 py-10 text-center text-sm text-(--muted-foreground)/60">
              Завершённых задач нет
            </div>
          ) : (
            <div className="flex flex-col">
              {filtered.map((todo) => (
                <TodoRow
                  key={todo.id}
                  todo={todo}
                  onComplete={() => incompleteTodo(todo.id)}
                />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
