// products/delphi/src/pages/ProjectPage.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, shallowRef, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { Circle, DollarSign, MoreHorizontal, Plus } from "@lucide/vue";
import { useQuickEntry } from "@/composables/useQuickEntry";
import { useSidebarState } from "@/composables/useSidebarState";

const { show: openQuickEntry } = useQuickEntry();
const {
  wrapClass,
  wrapStyle,
  titleWrapRef,
  titleGroupRef,
  titleGroupClass,
  titleGroupStyle,
  titleClass,
} = useSidebarState();
import { useTodoStore } from "@/store/todos";
import { storeToRefs } from "pinia";
import { ProjectStatus } from "@/types/task";
import {
  Button,
  ContextMenu,
  ContextMenuItem,
  EmptyState,
  IconButton,
  TodoRow,
} from "@kosmos/visuals";

// ---------------------------------------------------------------------------
// Color tag helper
// ---------------------------------------------------------------------------

function colorTagClass(colorTag?: string | null): string {
  switch (colorTag) {
    case "red":
      return "project-page__color--red";
    case "orange":
      return "project-page__color--orange";
    case "yellow":
      return "project-page__color--yellow";
    case "green":
      return "project-page__color--green";
    case "blue":
      return "project-page__color--blue";
    case "purple":
      return "project-page__color--purple";
    case "pink":
      return "project-page__color--pink";
    default:
      return "project-page__color--none";
  }
}

// ---------------------------------------------------------------------------
// Router & store
// ---------------------------------------------------------------------------

const router = useRouter();
const route = useRoute();
const store = useTodoStore();
const { projects } = storeToRefs(store);

const id = computed(() => route.params.id as string | undefined);

const project = computed(() => projects.value.find((p) => p.id === id.value));

const todos = computed(() => (id.value ? store.todosForProject(id.value) : []));

const activeTodos = computed(() => todos.value.filter((t) => !t.isCompleted && !t.isCancelled));

const completedTodos = computed(() => todos.value.filter((t) => t.isCompleted || t.isCancelled));

// ---------------------------------------------------------------------------
// Time entries — read from ARK and distribute price
// ---------------------------------------------------------------------------

interface TimeEntrySummary {
  taskId: string | null;
  billable: boolean;
  startedAt: string;
  endedAt: string | null;
}

const timeEntries = ref<TimeEntrySummary[]>([]);
let timeEntryPollHandle: ReturnType<typeof setInterval> | null = null;
const isElectronEnv = typeof window !== "undefined" && Boolean(window.electronAPI);

async function refreshTimeEntries() {
  if (!isElectronEnv) return;
  try {
    const result = (await window.electronAPI?.invoke("ark:listTimeEntries")) as
      | TimeEntrySummary[]
      | undefined;
    timeEntries.value = result ?? [];
  } catch {
    timeEntries.value = [];
  }
}

onMounted(() => {
  void refreshTimeEntries();
  timeEntryPollHandle = setInterval(refreshTimeEntries, 15000);
});

onUnmounted(() => {
  if (timeEntryPollHandle) clearInterval(timeEntryPollHandle);
});

function entryDurationSec(entry: TimeEntrySummary): number {
  const start = new Date(entry.startedAt).getTime();
  if (!Number.isFinite(start)) return 0;
  const end = entry.endedAt ? new Date(entry.endedAt).getTime() : Date.now();
  return Math.max(0, Math.floor((end - start) / 1000));
}

const billableSecondsByTask = computed(() => {
  const out = new Map<string, number>();
  for (const entry of timeEntries.value) {
    if (!entry.billable || !entry.taskId) continue;
    out.set(entry.taskId, (out.get(entry.taskId) ?? 0) + entryDurationSec(entry));
  }
  return out;
});

const totalBillableSeconds = computed(() => {
  let total = 0;
  for (const t of todos.value) {
    total += billableSecondsByTask.value.get(t.id) ?? 0;
  }
  return total;
});

const totalBillableHours = computed(() => totalBillableSeconds.value / 3600);

const projectHourlyRate = computed<number | null>(() => {
  const price = project.value?.price ?? null;
  if (price === null || totalBillableHours.value <= 0) return null;
  return price / totalBillableHours.value;
});

function formatHours(hours: number): string {
  return hours.toFixed(2).replace(/\.?0+$/, "") + " ч";
}

function formatPrice(value: number): string {
  return value.toFixed(value % 1 === 0 ? 0 : 2);
}

// ---------------------------------------------------------------------------
// Editable title
// ---------------------------------------------------------------------------

const editing = shallowRef(false);
const editTitle = shallowRef("");
const inputRef = ref<HTMLInputElement | null>(null);

watch(editing, async (val) => {
  if (val) {
    await nextTick();
    inputRef.value?.focus();
    inputRef.value?.select();
  }
});

function startRename() {
  if (!project.value) return;
  editTitle.value = project.value.title;
  editing.value = true;
  menuOpen.value = false;
}

function commitRename() {
  editing.value = false;
  const trimmed = editTitle.value.trim();
  if (project.value && trimmed && trimmed !== project.value.title) {
    store.updateProject(project.value.id, { title: trimmed });
  }
}

// ---------------------------------------------------------------------------
// Context menu
// ---------------------------------------------------------------------------

const menuOpen = shallowRef(false);
const menuX = shallowRef(0);
const menuY = shallowRef(0);

function toggleProjectMenu(event: MouseEvent) {
  const button = event.currentTarget as HTMLElement;
  const rect = button.getBoundingClientRect();
  menuX.value = Math.max(8, rect.right - 192);
  menuY.value = Math.max(8, rect.bottom + 4);
  menuOpen.value = !menuOpen.value;
}

function handleDrop(payload: { targetId: string; after: boolean }, sourceId: string) {
  if (sourceId === payload.targetId) return;
  const list = [...activeTodos.value];
  const srcIdx = list.findIndex((t) => t.id === sourceId);
  if (srcIdx === -1) return;
  const [item] = list.splice(srcIdx, 1);
  const tgtIdx = list.findIndex((t) => t.id === payload.targetId);
  if (tgtIdx === -1) return;
  list.splice(payload.after ? tgtIdx + 1 : tgtIdx, 0, item);
  list.forEach((t, i) => store.updateTodo(t.id, { sortOrder: i }));
}

function handleDelete() {
  if (!project.value) return;
  menuOpen.value = false;
  store.removeProject(project.value.id);
  router.push("/");
}

function handleArchive() {
  if (!project.value) return;
  menuOpen.value = false;
  store.updateProject(project.value.id, { status: ProjectStatus.Completed });
  router.push("/");
}
</script>

<template>
  <!-- Project not found -->
  <div v-if="!project" class="flex w-full min-w-0 flex-col items-center justify-center">
    <EmptyState title="Проект не найден" />
  </div>

  <!-- Project view -->
  <div v-else class="flex min-h-0 w-full min-w-0 flex-1 flex-col">
    <!-- Header -->
    <div
      ref="titleWrapRef"
      :class="[wrapClass, 'flex min-h-8 items-center gap-2.5 px-7 pb-3 pt-6']"
      :style="wrapStyle"
    >
      <Circle :size="12" :class="['shrink-0 fill-current', colorTagClass(project.colorTag)]" />

      <div ref="titleGroupRef" :class="titleGroupClass" :style="titleGroupStyle">
        <input
          v-if="editing"
          ref="inputRef"
          v-model="editTitle"
          :class="[
            titleClass,
            'bg-transparent text-2xl font-bold text-(--foreground) outline-none',
          ]"
          type="text"
          @blur="commitRename"
          @keydown.enter="commitRename"
          @keydown.escape="editing = false"
        />
        <h1
          v-else
          :class="[titleClass, 'text-2xl font-bold text-(--foreground) select-none cursor-pointer']"
          @dblclick="startRename"
        >
          {{ project.title }}
        </h1>

        <span v-if="todos.length > 0" class="text-sm text-(--muted-foreground)">
          {{ activeTodos.length }}
        </span>

        <span v-if="project.billable" class="project-page__billing-chip ml-2">
          <DollarSign :size="11" />
          <span v-if="project.price !== null && project.price !== undefined">
            {{ formatPrice(project.price) }}
          </span>
          <span v-else>оплачиваемый</span>
        </span>

        <span
          v-if="totalBillableSeconds > 0"
          class="ml-1 rounded-full bg-(--secondary) px-2.5 py-0.5 text-xs text-(--muted-foreground)"
          :title="
            projectHourlyRate !== null
              ? `${formatPrice(projectHourlyRate)} / час`
              : 'Сумма оплачиваемого времени по задачам проекта'
          "
        >
          {{ formatHours(totalBillableHours) }}
          <template v-if="projectHourlyRate !== null">
            · {{ formatPrice(projectHourlyRate) }}/ч
          </template>
        </span>
      </div>

      <!-- Context menu -->
      <div class="absolute right-7">
        <IconButton
          :size="32"
          :radius="8"
          aria-label="Меню проекта"
          title="Меню проекта"
          @click="toggleProjectMenu"
        >
          <MoreHorizontal :size="18" />
        </IconButton>

        <ContextMenu :open="menuOpen" :x="menuX" :y="menuY" @close="menuOpen = false">
          <ContextMenuItem @click="startRename"> Переименовать </ContextMenuItem>
          <ContextMenuItem @click="handleArchive"> Архивировать </ContextMenuItem>
          <div class="my-1 border-t border-(--border)" role="separator" />
          <ContextMenuItem destructive @click="handleDelete"> Удалить </ContextMenuItem>
        </ContextMenu>
      </div>
    </div>

    <!-- Task list -->
    <div class="scrollbar-gutter flex-1 overflow-y-auto">
      <div :class="[wrapClass, 'pb-20 pt-1']" :style="wrapStyle">
        <div v-if="activeTodos.length === 0 && completedTodos.length === 0" class="px-7 py-10">
          <EmptyState compact title="Нет задач в проекте" />
        </div>
        <template v-else>
          <div v-if="activeTodos.length > 0" class="flex flex-col">
            <TodoRow
              v-for="todo in activeTodos"
              :key="todo.id"
              :todo="todo"
              @complete="store.completeTodo(todo.id)"
              @trash="store.trashTodo(todo.id)"
              @update="store.updateTodo(todo.id, $event)"
              @drop="handleDrop($event, todo.id)"
            >
              <span
                v-if="(billableSecondsByTask.get(todo.id) ?? 0) > 0"
                class="rounded-full bg-(--secondary) px-2 py-0.5 text-[10px] text-(--muted-foreground)"
                :title="'Оплачиваемое время по задаче'"
              >
                {{ formatHours((billableSecondsByTask.get(todo.id) ?? 0) / 3600) }}
              </span>
            </TodoRow>
          </div>

          <template v-if="completedTodos.length > 0">
            <div
              class="px-7 pb-1 pt-4 text-xs font-semibold uppercase tracking-wider text-(--muted-foreground)/60 select-none"
            >
              Завершённые ({{ completedTodos.length }})
            </div>
            <div class="flex flex-col">
              <TodoRow
                v-for="todo in completedTodos"
                :key="todo.id"
                :todo="todo"
                @complete="store.completeTodo(todo.id)"
              />
            </div>
          </template>
        </template>
      </div>
    </div>

    <Button
      type="button"
      variant="primary"
      class="absolute bottom-6 right-6"
      title="Новая задача (⌘N)"
      aria-label="Новая задача"
      @click="openQuickEntry"
    >
      <template #icon>
        <Plus :size="16" />
      </template>
      Новая задача
    </Button>
  </div>
</template>

<style scoped>
.project-page__color--none {
  color: var(--muted-foreground);
}

.project-page__color--red {
  color: var(--destructive);
}

.project-page__color--orange {
  color: color-mix(in srgb, var(--status-warning) 78%, var(--destructive));
}

.project-page__color--yellow {
  color: var(--status-warning);
}

.project-page__color--green {
  color: var(--status-success);
}

.project-page__color--blue {
  color: var(--accent);
}

.project-page__color--purple {
  color: color-mix(in srgb, var(--accent) 70%, var(--destructive));
}

.project-page__color--pink {
  color: color-mix(in srgb, var(--destructive) 65%, var(--accent));
}

.project-page__billing-chip {
  display: flex;
  align-items: center;
  gap: 4px;
  border-radius: 999px;
  padding: 2px 10px;
  color: var(--status-success);
  background: color-mix(in srgb, var(--status-success) 15%, transparent);
  font-size: var(--kosmos-text-caption-size);
}
</style>

// apps/delphi/ts/src/pages/ProjectPage.tsx
import { useParams, useNavigate } from 'react-router-dom';
import { useEffect, useRef, useState } from 'react';
import { Circle, MoreHorizontal } from 'lucide-react';
import useTodoStore from '@/store/todos';
import { ProjectStatus } from '@/types/task';

/** Map colorTag strings to Tailwind text color classes. */
function colorTagClass(colorTag?: string | null): string {
  switch (colorTag) {
    case 'red': return 'text-red-500';
    case 'orange': return 'text-orange-500';
    case 'yellow': return 'text-yellow-500';
    case 'green': return 'text-green-500';
    case 'blue': return 'text-blue-500';
    case 'purple': return 'text-purple-500';
    case 'pink': return 'text-pink-500';
    default: return 'text-(--muted-foreground)';
  }
}
import TodoRow from '@/components/TodoRow';
import { arkSync, projectToArkChange } from '@/services/sync/ark-client';

export default function ProjectPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const projects = useTodoStore((s) => s.projects);
  const updateProject = useTodoStore((s) => s.updateProject);
  const removeProject = useTodoStore((s) => s.removeProject);
  const todosForProject = useTodoStore((s) => s.todosForProject);
  const completeTodo = useTodoStore((s) => s.completeTodo);
  const trashTodo = useTodoStore((s) => s.trashTodo);

  const project = projects.find((p) => p.id === id);
  const todos = id ? todosForProject(id) : [];

  const [editing, setEditing] = useState(false);
  const [editTitle, setEditTitle] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (editing && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [editing]);

  // Close menu on outside click
  useEffect(() => {
    if (!menuOpen) return;
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setMenuOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [menuOpen]);

  if (!project) {
    return (
      <div className="flex w-full min-w-0 flex-col items-center justify-center">
        <p className="text-(--muted-foreground)">Проект не найден</p>
      </div>
    );
  }

  const startRename = () => {
    setEditTitle(project.title);
    setEditing(true);
    setMenuOpen(false);
  };

  const commitRename = () => {
    setEditing(false);
    const trimmed = editTitle.trim();
    if (trimmed && trimmed !== project.title) {
      updateProject(project.id, { title: trimmed });
      arkSync.sendChange(
        projectToArkChange({ ...project, title: trimmed }, 'update'),
      );
    }
  };

  const handleDelete = () => {
    setMenuOpen(false);
    removeProject(project.id);
    arkSync.sendChange(projectToArkChange(project, 'delete'));
    navigate('/');
  };

  const handleArchive = () => {
    setMenuOpen(false);
    updateProject(project.id, { status: ProjectStatus.Completed });
    arkSync.sendChange(
      projectToArkChange({ ...project, status: ProjectStatus.Completed }, 'update'),
    );
    navigate('/');
  };

  const activeTodos = todos.filter((t) => !t.isCompleted && !t.isCancelled);
  const completedTodos = todos.filter((t) => t.isCompleted || t.isCancelled);

  return (
    <div className="flex w-full min-w-0 flex-col">
      {/* Header */}
      <div className="flex items-center gap-2.5 px-7 pb-3 pt-6">
        <Circle
          size={12}
          className={`shrink-0 fill-current ${colorTagClass(project.colorTag)}`}
        />

        {editing ? (
          <input
            ref={inputRef}
            type="text"
            value={editTitle}
            onChange={(e) => setEditTitle(e.target.value)}
            onBlur={commitRename}
            onKeyDown={(e) => {
              if (e.key === 'Enter') commitRename();
              if (e.key === 'Escape') setEditing(false);
            }}
            className="flex-1 bg-transparent text-2xl font-bold text-(--foreground) outline-none"
          />
        ) : (
          <h1
            className="text-2xl font-bold text-(--foreground) select-none cursor-pointer"
            onDoubleClick={startRename}
          >
            {project.title}
          </h1>
        )}

        {todos.length > 0 && (
          <span className="text-sm text-(--muted-foreground)">{activeTodos.length}</span>
        )}

        {/* Context menu */}
        <div className="relative ml-auto" ref={menuRef}>
          <button
            type="button"
            onClick={() => setMenuOpen((v) => !v)}
            className="rounded p-1 text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)"
          >
            <MoreHorizontal size={18} />
          </button>

          {menuOpen && (
            <div className="absolute right-0 top-full z-50 mt-1 w-44 rounded-lg border border-(--border) bg-(--popover) py-1 shadow-lg">
              <button
                type="button"
                onClick={startRename}
                className="flex w-full items-center px-3 py-2 text-sm text-(--foreground) hover:bg-(--secondary)"
              >
                Переименовать
              </button>
              <button
                type="button"
                onClick={handleArchive}
                className="flex w-full items-center px-3 py-2 text-sm text-(--foreground) hover:bg-(--secondary)"
              >
                Архивировать
              </button>
              <div className="my-1 border-t border-(--border)" />
              <button
                type="button"
                onClick={handleDelete}
                className="flex w-full items-center px-3 py-2 text-sm text-red-500 hover:bg-red-500/10"
              >
                Удалить
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Task list */}
      <div className="scrollbar-gutter flex-1 overflow-y-auto">
        <div className="pb-20 pt-1">
          {activeTodos.length === 0 && completedTodos.length === 0 ? (
            <div className="px-7 py-10 text-center text-sm text-(--muted-foreground)/60">
              Нет задач в проекте
            </div>
          ) : (
            <>
              {activeTodos.length > 0 && (
                <div className="flex flex-col">
                  {activeTodos.map((todo) => (
                    <TodoRow
                      key={todo.id}
                      todo={todo}
                      onComplete={() => completeTodo(todo.id)}
                      onTrash={() => trashTodo(todo.id)}
                    />
                  ))}
                </div>
              )}

              {completedTodos.length > 0 && (
                <>
                  <div className="px-7 pb-1 pt-4 text-xs font-semibold uppercase tracking-wider text-(--muted-foreground)/60 select-none">
                    Завершённые ({completedTodos.length})
                  </div>
                  <div className="flex flex-col">
                    {completedTodos.map((todo) => (
                      <TodoRow
                        key={todo.id}
                        todo={todo}
                        onComplete={() => completeTodo(todo.id)}
                      />
                    ))}
                  </div>
                </>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
