// apps/delphi/ts/src/pages/TodayPage.tsx
import { Star } from "lucide-react";
import useSmartList from "@/hooks/useSmartList";
import { SmartList } from "@/types/task";
import TodoRow from "@/components/TodoRow";
import useTodoStore from "@/store/todos";

export default function TodayPage() {
  const { filtered } = useSmartList(SmartList.Today);
  const completeTodo = useTodoStore((s) => s.completeTodo);
  const trashTodo = useTodoStore((s) => s.trashTodo);
  const updateTodo = useTodoStore((s) => s.updateTodo);

  return (
    <div className="flex w-full min-w-0 flex-col">
      <div className="flex items-center gap-2.5 px-7 pb-3 pt-6">
        <Star size={24} className="text-yellow-500" />
        <h1 className="text-2xl font-bold text-(--foreground) select-none">
          Сегодня
        </h1>
        {filtered.length > 0 && (
          <span className="text-sm text-(--muted-foreground)">
            {filtered.length}
          </span>
        )}
      </div>

      <div className="scrollbar-gutter flex-1 overflow-y-auto">
        <div className="pb-20 pt-1">
          {filtered.length === 0 ? (
            <div className="px-7 py-10 text-center text-sm text-(--muted-foreground)/60">
              На сегодня задач нет
            </div>
          ) : (
            <div className="flex flex-col">
              {filtered.map((todo) => (
                <TodoRow
                  key={todo.id}
                  todo={todo}
                  onComplete={() => completeTodo(todo.id)}
                  onTrash={() => trashTodo(todo.id)}
                  onRename={(title) => updateTodo(todo.id, { title })}
                  extra={
                    todo.isEvening ? (
                      <span className="text-[10px] text-indigo-400">Вечер</span>
                    ) : null
                  }
                />
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// apps/delphi/ts/src/pages/TodayPage.vue
<script setup lang="ts">
import { computed } from "vue";
import { Star, Plus } from "lucide-vue-next";
import { useQuickEntry } from "@/composables/useQuickEntry";

const { show: openQuickEntry } = useQuickEntry();
import { SmartList } from "@/types/task";
import { useTodoStore } from "@/store/todos";
import { storeToRefs } from "pinia";
import { filterTodos } from "@/services/filters/todoFilterService";
import TodoRow from "@/components/TodoRow.vue";

const store = useTodoStore();
const { todos } = storeToRefs(store);
const filtered = computed(() => filterTodos(SmartList.Today, todos.value));
</script>

<template>
  <div class="flex min-h-0 w-full min-w-0 flex-1 flex-col">
    <div class="flex items-center gap-2.5 px-7 pb-3 pt-6">
      <Star :size="24" class="text-yellow-500" />
      <h1 class="text-2xl font-bold text-(--foreground) select-none">
        Сегодня
      </h1>
      <span
        v-if="filtered.length > 0"
        class="text-sm text-(--muted-foreground)"
      >
        {{ filtered.length }}
      </span>
    </div>

    <div class="scrollbar-gutter flex-1 overflow-y-auto">
      <div class="pb-20 pt-1">
        <div
          v-if="filtered.length === 0"
          class="px-7 py-10 text-center text-sm text-(--muted-foreground)/60"
        >
          На сегодня задач нет
        </div>
        <div v-else class="flex flex-col">
          <TodoRow
            v-for="todo in filtered"
            :key="todo.id"
            :todo="todo"
            @complete="store.completeTodo(todo.id)"
            @trash="store.trashTodo(todo.id)"
            @rename="store.updateTodo(todo.id, { title: $event })"
          >
            <span v-if="todo.isEvening" class="text-[10px] text-indigo-400"
              >Вечер</span
            >
          </TodoRow>
        </div>
      </div>
    </div>

    <button
      type="button"
      class="absolute bottom-6 right-6 flex h-12 w-12 items-center justify-center rounded-full bg-(--primary) text-(--primary-foreground) shadow-lg transition-transform hover:scale-105 active:scale-95"
      title="Новая задача (⌘N)"
      @click="openQuickEntry"
    >
      <Plus :size="24" />
    </button>
  </div>
</template>
