// apps/eden/ts/src/Editor.vue
<template>
  <div class="editor-wrapper">
    <div class="editor-header">
      <div class="editor-rail editor-header-rail">
        <div class="editor-header-main">
          <TypedHeader
            :active-note-type="activeNoteType"
            :title="title"
            :header-props="headerProps"
            :validation-error="headerValidationError"
            @header-prop-change="handleHeaderPropChange"
          />
          <input v-model="title" class="title-input" placeholder="Заголовок" />
          <div ref="noteTypeMenuRef" class="note-type-inline">
            <button
              class="note-type-trigger"
              data-testid="typed-note-trigger"
              type="button"
              :style="{ '--note-type-accent': activeNoteType?.color ?? 'var(--text-tertiary)' }"
              @click="isNoteTypeMenuOpen = !isNoteTypeMenuOpen"
            >
              {{ activeNoteType?.name ?? "Обычная заметка" }}
            </button>
            <div v-if="isNoteTypeMenuOpen" class="note-type-menu" data-testid="typed-note-menu">
              <button
                :class="['note-type-menu-item', !noteTypeId && 'is-active']"
                type="button"
                @click="handleNoteTypeChange('')"
              >
                Обычная заметка
              </button>
              <button
                v-for="noteType in noteTypes"
                :key="noteType.id"
                :class="['note-type-menu-item', noteType.id === noteTypeId && 'is-active']"
                type="button"
                @click="handleNoteTypeChange(noteType.id)"
              >
                {{ noteType.name }}
              </button>
            </div>
          </div>
        </div>
        <div class="editor-header-actions">
          <span v-if="saveConflict" class="save-conflict-badge">{{ saveConflict }}</span>
        </div>
      </div>
    </div>
    <div class="editor-content-area" @click="editor?.commands.focus()">
      <div class="editor-rail editor-content-rail">
        <EditorContent :editor="editor ?? null" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, watchEffect, nextTick } from "vue";
import { useEditor, EditorContent, VueRenderer, VueNodeViewRenderer } from "@tiptap/vue-3";
import StarterKit from "@tiptap/starter-kit";
import { Markdown } from "@tiptap/markdown";
import Placeholder from "@tiptap/extension-placeholder";
import CodeBlockLowlight from "@tiptap/extension-code-block-lowlight";
import { all, createLowlight } from "lowlight";
import Typography from "@tiptap/extension-typography";
import type { Editor as TiptapEditor, Range } from "@tiptap/vue-3";
import type { Instance } from "tippy.js";
import tippy from "tippy.js";
import { Wikilink } from "./Wikilink";
import WikilinkList from "./WikilinkList.vue";
import { SlashCommand } from "./SlashCommand";
import SlashCommandList from "./SlashCommandList.vue";
import TypedHeader from "@/components/typed-notes/TypedHeader.vue";
import CodeBlockView from "@/components/CodeBlockView.vue";
import {
  createDefaultHeaderProps,
  parseHeaderTemplate,
  safeParseHeaderProps,
  validateHeaderProps,
} from "@/lib/typedNotes";
import { resolveLanguageId } from "@/lib/codeBlocks";
import "./Editor.css";

const props = defineProps<{
  entry: Entry;
  allEntries: Entry[];
  noteTypes: NoteType[];
  codeToolsSettings: CodeToolsSettings | null;
  onSave: (entry: Entry) => Promise<SaveEntryResult | null>;
  onNavigate: (entryId: string) => void;
}>();

// --- State ---
const title = ref(props.entry.title);
const noteTypeId = ref<string | null>(props.entry.type_id);
const headerLayout = ref<string | null>(props.entry.header_layout);
const headerProps = ref<Record<string, unknown>>(
  safeParseHeaderProps(null, props.entry.header_props_json),
);
const saveConflict = ref<string | null>(null);
const headerValidationError = ref<string | null>(null);
const isNoteTypeMenuOpen = ref(false);
const noteTypeMenuRef = ref<HTMLDivElement | null>(null);
const docVersion = ref(0);

// Non-reactive tracking (mirrors React useRef pattern)
let lastSavedSnapshot = "";
let saveRunId = 0;
let lintRunId = 0;

// Live reference to allEntries for suggestion closures
const allEntriesHolder = { current: props.allEntries };
watch(
  () => props.allEntries,
  (v) => {
    allEntriesHolder.current = v;
  },
  { immediate: true },
);

// --- Computed ---
const activeNoteType = computed(
  () => props.noteTypes.find((nt) => nt.id === noteTypeId.value) ?? null,
);

// --- TipTap setup ---
const lowlight = createLowlight(all);

const EdenCodeBlock = CodeBlockLowlight.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      wrap: {
        default: true,
        parseHTML: (element: HTMLElement) => element.getAttribute("data-wrap") !== "false",
        renderHTML: (attributes: { wrap?: boolean }) => ({
          "data-wrap": attributes.wrap === false ? "false" : "true",
        }),
      },
    };
  },
  addNodeView() {
    return VueNodeViewRenderer(CodeBlockView);
  },
});

const extensions = [
  StarterKit.configure({ codeBlock: false }),
  Markdown,
  Placeholder.configure({ placeholder: "Начни писать что-нибудь интересное..." }),
  EdenCodeBlock.configure({
    lowlight,
    enableTabIndentation: true,
    tabSize: 4,
    defaultLanguage: null,
  }),
  Typography,
  Wikilink.configure({
    suggestion: {
      items: ({ query }: { query: string }) =>
        allEntriesHolder.current
          .filter((item) => item.title.toLowerCase().includes(query.toLowerCase()))
          .slice(0, 10),
      render: () => {
        let component: InstanceType<typeof VueRenderer>;
        let popup: Instance[];

        return {
          onStart: (renderProps: any) => {
            component = new VueRenderer(WikilinkList, {
              props: renderProps,
              editor: renderProps.editor,
            });
            if (!renderProps.clientRect) return;
            popup = tippy("body", {
              getReferenceClientRect: renderProps.clientRect,
              appendTo: () => document.body,
              content: component.element,
              showOnCreate: true,
              interactive: true,
              trigger: "manual",
              placement: "bottom-start",
            });
          },
          onUpdate(renderProps: any) {
            component.updateProps(renderProps);
            if (!renderProps.clientRect) return;
            popup[0].setProps({ getReferenceClientRect: renderProps.clientRect });
          },
          onKeyDown(renderProps: any) {
            if (renderProps.event.key === "Escape") {
              popup[0].hide();
              return true;
            }
            return (component.ref as any)?.onKeyDown(renderProps) ?? false;
          },
          onExit() {
            popup[0].destroy();
            component.destroy();
          },
        };
      },
    },
  }),
  SlashCommand.configure({
    suggestion: {
      items: ({ query }: { query: string }) =>
        [
          {
            title: "Заголовок 1",
            description: "Большой заголовок раздела",
            icon: "H1",
            command: ({ editor, range }: { editor: TiptapEditor; range: Range }) =>
              editor.chain().focus().deleteRange(range).setNode("heading", { level: 1 }).run(),
          },
          {
            title: "Заголовок 2",
            description: "Средний заголовок",
            icon: "H2",
            command: ({ editor, range }: { editor: TiptapEditor; range: Range }) =>
              editor.chain().focus().deleteRange(range).setNode("heading", { level: 2 }).run(),
          },
          {
            title: "Текст",
            description: "Обычный абзац",
            icon: "P",
            command: ({ editor, range }: { editor: TiptapEditor; range: Range }) =>
              editor.chain().focus().deleteRange(range).setNode("paragraph").run(),
          },
          {
            title: "Список",
            description: "Маркированный список",
            icon: "•",
            command: ({ editor, range }: { editor: TiptapEditor; range: Range }) =>
              editor.chain().focus().deleteRange(range).toggleBulletList().run(),
          },
          {
            title: "Код",
            description: "Блок кода с подсветкой",
            icon: "{}",
            command: ({ editor, range }: { editor: TiptapEditor; range: Range }) =>
              editor.chain().focus().deleteRange(range).toggleCodeBlock().run(),
          },
          {
            title: "Цитата",
            description: "Блок цитирования",
            icon: '"',
            command: ({ editor, range }: { editor: TiptapEditor; range: Range }) =>
              editor.chain().focus().deleteRange(range).toggleBlockquote().run(),
          },
        ].filter((item) => item.title.toLowerCase().includes(query.toLowerCase())),
      render: () => {
        let component: InstanceType<typeof VueRenderer>;
        let popup: Instance[];

        return {
          onStart: (renderProps: any) => {
            component = new VueRenderer(SlashCommandList, {
              props: renderProps,
              editor: renderProps.editor,
            });
            if (!renderProps.clientRect) return;
            popup = tippy("body", {
              getReferenceClientRect: renderProps.clientRect,
              appendTo: () => document.body,
              content: component.element,
              showOnCreate: true,
              interactive: true,
              trigger: "manual",
              placement: "bottom-start",
            });
          },
          onUpdate(renderProps: any) {
            component.updateProps(renderProps);
            if (!renderProps.clientRect) return;
            popup[0].setProps({ getReferenceClientRect: renderProps.clientRect });
          },
          onKeyDown(renderProps: any) {
            if (renderProps.event.key === "Escape") {
              popup[0].hide();
              return true;
            }
            return (component.ref as any)?.onKeyDown(renderProps) ?? false;
          },
          onExit() {
            popup[0].destroy();
            component.destroy();
          },
        };
      },
    },
  }),
];

const editor = useEditor({
  extensions,
  content: (() => {
    try {
      return props.entry.content_json
        ? JSON.parse(props.entry.content_json)
        : { type: "doc", content: [{ type: "paragraph" }] };
    } catch {
      return { type: "doc", content: [{ type: "paragraph" }] };
    }
  })(),
  autofocus: "end",
  editable: true,
  onUpdate: () => {
    docVersion.value++;
  },
});

// --- Helpers ---

function getCurrentSnapshot(): string | null {
  if (!editor.value) return null;
  return JSON.stringify({
    title: title.value || "Без названия",
    noteTypeId: noteTypeId.value,
    headerLayout: headerLayout.value,
    headerProps: headerProps.value,
    doc: editor.value.getJSON(),
    markdown: editor.value.storage?.markdown?.getMarkdown?.() ?? "",
  });
}

function applyCodeBlockText(nodePos: number, nextCode: string): boolean {
  if (!editor.value) return false;
  const codeBlockNode = editor.value.state.doc.nodeAt(nodePos);
  if (!codeBlockNode) return false;
  const contentFrom = nodePos + 1;
  const contentTo = nodePos + codeBlockNode.nodeSize - 1;
  const tr = editor.value.state.tr;
  if (contentTo > contentFrom) tr.delete(contentFrom, contentTo);
  if (nextCode.length > 0) tr.insertText(nextCode, contentFrom);
  editor.value.view.dispatch(tr);
  return true;
}

async function formatAllCodeBlocks() {
  if (!editor.value || !props.codeToolsSettings) return;
  const blocks: Array<{ nodePos: number; code: string; language: string }> = [];
  editor.value.state.doc.descendants((node, position) => {
    if (node.type.name === "codeBlock") {
      blocks.push({
        nodePos: position,
        code: node.textContent,
        language: resolveLanguageId((node.attrs as { language?: string | null }).language),
      });
    }
    return true;
  });
  for (const block of [...blocks].reverse()) {
    const result = await window.api.formatCodeBlock(block.language, block.code);
    if (result.code !== block.code) applyCodeBlockText(block.nodePos, result.code);
  }
}

async function lintAllCodeBlocks() {
  if (!editor.value || !props.codeToolsSettings) return;
  const runId = ++lintRunId;
  const blocks: Array<{ nodePos: number; code: string; language: string }> = [];
  editor.value.state.doc.descendants((node, position) => {
    if (node.type.name === "codeBlock") {
      blocks.push({
        nodePos: position,
        code: node.textContent,
        language: resolveLanguageId((node.attrs as { language?: string | null }).language),
      });
    }
    return true;
  });
  for (const block of blocks) {
    await window.api.lintCodeBlock(block.language, block.code);
  }
  if (runId !== lintRunId) return;
}

async function save() {
  if (!editor.value) return;

  const headerValidation = validateHeaderProps(activeNoteType.value, headerProps.value);
  if (!headerValidation.success) {
    headerValidationError.value = "Проверьте поля верхушки заметки";
    return;
  }

  headerValidationError.value = null;

  const snapshotBeforeSave = getCurrentSnapshot();
  if (!snapshotBeforeSave || lastSavedSnapshot === snapshotBeforeSave) return;

  const currentSaveRunId = ++saveRunId;

  if (props.codeToolsSettings?.formatOnSave) await formatAllCodeBlocks();
  if (props.codeToolsSettings?.lintTrigger === "on_save") await lintAllCodeBlocks();

  const content_json = JSON.stringify(editor.value.getJSON());

  const saveResult = await props.onSave({
    ...props.entry,
    title: title.value || "Без названия",
    content_json,
    type_id: noteTypeId.value,
    header_layout: headerLayout.value,
    header_props_json: JSON.stringify(headerValidation.data),
    schema_version: 1,
    updated_at: Date.now(),
  });

  if (!saveResult) return;
  if (currentSaveRunId !== saveRunId) return;

  if (!saveResult.ok && saveResult.reason === "duplicate_title") {
    saveConflict.value = "Заметка с таким названием уже есть в этой папке";
    return;
  }

  if (!saveResult.ok && saveResult.reason === "invalid_type_metadata") {
    headerValidationError.value = saveResult.message;
    return;
  }

  saveConflict.value = null;
  lastSavedSnapshot = getCurrentSnapshot() ?? snapshotBeforeSave;
}

function handleNoteTypeChange(nextTypeId: string) {
  const nextNoteType = props.noteTypes.find((nt) => nt.id === nextTypeId) ?? null;
  noteTypeId.value = nextTypeId || null;
  headerLayout.value = nextNoteType
    ? parseHeaderTemplate(nextNoteType.header_template_json).kind
    : null;
  headerProps.value = createDefaultHeaderProps(nextNoteType);
  headerValidationError.value = null;
  isNoteTypeMenuOpen.value = false;
}

function handleHeaderPropChange(fieldId: string, value: unknown) {
  headerProps.value = { ...headerProps.value, [fieldId]: value };
}

// --- Watchers ---

// Sync editor content when entry changes externally
watch(
  () => props.entry.content_json,
  (contentJson) => {
    if (!editor.value) return;
    try {
      const parsed = contentJson
        ? JSON.parse(contentJson)
        : { type: "doc", content: [{ type: "paragraph" }] };
      const current = editor.value.getJSON();
      if (JSON.stringify(current) !== JSON.stringify(parsed)) {
        editor.value.commands.setContent(parsed);
      }
    } catch (e) {
      console.error("Failed to parse content_json", e);
    }
  },
);

// Reset state when switching entries
watch(
  () => props.entry.id,
  () => {
    saveConflict.value = null;
  },
);

// Reset snapshot baseline when editor loads or entry changes
watch([editor, () => props.entry.id, () => props.entry.updated_at], () => {
  if (!editor.value) return;
  lastSavedSnapshot = getCurrentSnapshot() ?? "";
});

// Sync header state when entry metadata changes
watch(
  [
    () => props.entry.id,
    () => props.entry.type_id,
    () => props.entry.header_props_json,
    () => props.entry.header_layout,
    () => props.noteTypes,
  ],
  () => {
    noteTypeId.value = props.entry.type_id;
    headerLayout.value = props.entry.header_layout;
    const nextNoteType = props.noteTypes.find((nt) => nt.id === props.entry.type_id) ?? null;
    headerProps.value = safeParseHeaderProps(nextNoteType, props.entry.header_props_json);
    headerValidationError.value = null;
  },
);

// Clear saveConflict on title change
watch(title, () => {
  saveConflict.value = null;
});

// Auto-save: 800ms debounce on doc or title change
watchEffect((onCleanup) => {
  const _d = docVersion.value;
  const _t = title.value;
  const timer = setTimeout(() => {
    void save();
  }, 800);
  onCleanup(() => clearTimeout(timer));
});

// Lint on idle: 1000ms debounce
watchEffect((onCleanup) => {
  if (props.codeToolsSettings?.lintTrigger !== "on_idle") return;
  const _d = docVersion.value;
  const timer = window.setTimeout(() => {
    void lintAllCodeBlocks();
  }, 1000);
  onCleanup(() => window.clearTimeout(timer));
});

// Ctrl+S save handler
watchEffect((onCleanup) => {
  if (!editor.value) return;
  const handleKeyDown = (e: KeyboardEvent) => {
    if ((e.metaKey || e.ctrlKey) && e.key === "s") {
      e.preventDefault();
      void save();
    }
  };
  document.addEventListener("keydown", handleKeyDown);
  onCleanup(() => document.removeEventListener("keydown", handleKeyDown));
});

// Wikilink click navigation
watchEffect((onCleanup) => {
  if (!editor.value) return;
  const handleClick = (event: MouseEvent) => {
    const target = event.target as HTMLElement;
    const wikilink = target.closest("span[data-id]");
    if (wikilink) {
      const entryId = wikilink.getAttribute("data-id");
      if (entryId) props.onNavigate(entryId);
    }
  };
  const dom = editor.value.view.dom;
  dom.addEventListener("click", handleClick);
  onCleanup(() => dom.removeEventListener("click", handleClick));
});

// Note type menu close on click-outside / Escape
watchEffect((onCleanup) => {
  if (!isNoteTypeMenuOpen.value) return;

  const handlePointerDown = (event: MouseEvent) => {
    if (noteTypeMenuRef.value?.contains(event.target as Node)) return;
    isNoteTypeMenuOpen.value = false;
  };
  const handleEscape = (event: KeyboardEvent) => {
    if (event.key === "Escape") isNoteTypeMenuOpen.value = false;
  };

  window.addEventListener("mousedown", handlePointerDown);
  window.addEventListener("keydown", handleEscape);
  onCleanup(() => {
    window.removeEventListener("mousedown", handlePointerDown);
    window.removeEventListener("keydown", handleEscape);
  });
});

// Focus editor when entry changes
watch(
  () => props.entry.id,
  () => {
    nextTick(() => editor.value?.commands.focus("end"));
  },
);
</script>

// apps/eden/ts/src/Editor.tsx
import { useEditor, EditorContent, Editor as TiptapEditor, ReactRenderer, Range, NodeViewWrapper, NodeViewContent, ReactNodeViewRenderer } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import { Markdown } from '@tiptap/markdown'
import Placeholder from '@tiptap/extension-placeholder'
import CodeBlockLowlight from '@tiptap/extension-code-block-lowlight'
import { all, createLowlight } from 'lowlight'
import { Wikilink } from './Wikilink'
import { WikilinkList, WikilinkListRef } from './WikilinkList'
import { SlashCommand } from './SlashCommand'
import { SlashCommandList, SlashCommandListRef } from './SlashCommandList'
import tippy, { Instance } from 'tippy.js'
import Typography from '@tiptap/extension-typography'
import { useEffect, useState, useCallback, useMemo, useRef, type CSSProperties } from 'react'
import TypedHeader from '@/components/typed-notes/TypedHeader'
import { createDefaultHeaderProps, parseHeaderTemplate, safeParseHeaderProps, validateHeaderProps } from '@/lib/typedNotes'
import './Editor.css'

const lowlight = createLowlight(all)

const codeBlockLanguages: { id: string; name: string }[] = [
  { id: 'plaintext', name: 'Plain Text' },
  { id: 'arduino', name: 'Arduino' },
  { id: 'bash', name: 'Bash' },
  { id: 'c', name: 'C' },
  { id: 'cpp', name: 'C++' },
  { id: 'csharp', name: 'C#' },
  { id: 'clojure', name: 'Clojure' },
  { id: 'coffeescript', name: 'CoffeeScript' },
  { id: 'css', name: 'CSS' },
  { id: 'dart', name: 'Dart' },
  { id: 'diff', name: 'Diff' },
  { id: 'dockerfile', name: 'Dockerfile' },
  { id: 'elixir', name: 'Elixir' },
  { id: 'elm', name: 'Elm' },
  { id: 'erlang', name: 'Erlang' },
  { id: 'fortran', name: 'Fortran' },
  { id: 'fsharp', name: 'F#' },
  { id: 'glsl', name: 'GLSL' },
  { id: 'go', name: 'Go' },
  { id: 'graphql', name: 'GraphQL' },
  { id: 'groovy', name: 'Groovy' },
  { id: 'haskell', name: 'Haskell' },
  { id: 'html', name: 'HTML' },
  { id: 'ini', name: 'INI' },
  { id: 'java', name: 'Java' },
  { id: 'javascript', name: 'JavaScript' },
  { id: 'json', name: 'JSON' },
  { id: 'julia', name: 'Julia' },
  { id: 'kotlin', name: 'Kotlin' },
  { id: 'latex', name: 'LaTeX' },
  { id: 'less', name: 'Less' },
  { id: 'lisp', name: 'Lisp' },
  { id: 'lua', name: 'Lua' },
  { id: 'makefile', name: 'Makefile' },
  { id: 'markdown', name: 'Markdown' },
  { id: 'matlab', name: 'MATLAB' },
  { id: 'nix', name: 'Nix' },
  { id: 'objectivec', name: 'Objective-C' },
  { id: 'ocaml', name: 'OCaml' },
  { id: 'pascal', name: 'Pascal' },
  { id: 'perl', name: 'Perl' },
  { id: 'php', name: 'PHP' },
  { id: 'powershell', name: 'PowerShell' },
  { id: 'protobuf', name: 'Protobuf' },
  { id: 'python', name: 'Python' },
  { id: 'r', name: 'R' },
  { id: 'ruby', name: 'Ruby' },
  { id: 'rust', name: 'Rust' },
  { id: 'scala', name: 'Scala' },
  { id: 'scss', name: 'SCSS' },
  { id: 'shell', name: 'Shell' },
  { id: 'sql', name: 'SQL' },
  { id: 'swift', name: 'Swift' },
  { id: 'toml', name: 'TOML' },
  { id: 'typescript', name: 'TypeScript' },
  { id: 'vbnet', name: 'VB.NET' },
  { id: 'verilog', name: 'Verilog' },
  { id: 'vhdl', name: 'VHDL' },
  { id: 'wasm', name: 'WebAssembly' },
  { id: 'xml', name: 'XML' },
  { id: 'yaml', name: 'YAML' },
  { id: 'zig', name: 'Zig' },
]

const codeBlockLanguageMap = new Map(codeBlockLanguages.map(lang => [lang.id, lang.name]))

const codeLanguageAliases: Record<string, string> = {
  js: 'javascript',
  ts: 'typescript',
  py: 'python',
  rb: 'ruby',
  rs: 'rust',
  cs: 'csharp',
  'c++': 'cpp',
  'c#': 'csharp',
  'f#': 'fsharp',
  sh: 'bash',
  zsh: 'bash',
  yml: 'yaml',
  tex: 'latex',
  kt: 'kotlin',
  objc: 'objectivec',
  'objective-c': 'objectivec',
  ps: 'powershell',
  ps1: 'powershell',
  proto: 'protobuf',
  hs: 'haskell',
  ex: 'elixir',
  erl: 'erlang',
  ml: 'ocaml',
  vb: 'vbnet',
  asm: 'wasm',
  plain: 'plaintext',
  text: 'plaintext',
  txt: 'plaintext',
}

function resolveLanguageId(language: string | null | undefined): string {
  if (!language || !language.trim()) return 'plaintext'
  const lower = language.toLowerCase()
  return codeLanguageAliases[lower] ?? lower
}

function getCodeLanguageDisplayName(languageId: string) {
  return codeBlockLanguageMap.get(languageId) ?? languageId
}

function CodeBlockView({ node, updateAttributes }: { node: any; updateAttributes: (attrs: Record<string, any>) => void }) {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const [langSearch, setLangSearch] = useState('')
  const langSearchRef = useRef<HTMLInputElement>(null)

  const language = resolveLanguageId(node.attrs.language)
  const isWrapped = node.attrs.wrap !== false

  useEffect(() => {
    if (!isMenuOpen) return
    const close = () => { setIsMenuOpen(false); setLangSearch('') }
    const timer = setTimeout(() => document.addEventListener('click', close), 0)
    return () => { clearTimeout(timer); document.removeEventListener('click', close) }
  }, [isMenuOpen])

  useEffect(() => {
    if (isMenuOpen) setTimeout(() => langSearchRef.current?.focus(), 0)
  }, [isMenuOpen])

  return (
    <NodeViewWrapper className="code-block-node">
      <div className="code-block-actions" contentEditable={false}>
        <div className="code-block-actions-left">
          <button
            className="code-block-lang-btn"
            onClick={(e) => {
              e.stopPropagation()
              setIsMenuOpen(!isMenuOpen)
              setLangSearch('')
            }}
            type="button"
          >
            {getCodeLanguageDisplayName(language)}
            <svg className="code-block-lang-arrow" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
          {isMenuOpen && (
            <div className="code-tools-menu" onClick={(e) => e.stopPropagation()}>
              <input
                ref={langSearchRef}
                className="code-tools-search"
                type="text"
                placeholder="Search..."
                value={langSearch}
                onChange={(e) => setLangSearch(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Escape') { setIsMenuOpen(false); setLangSearch('') } }}
              />
              <div className="code-tools-languages">
                {codeBlockLanguages
                  .filter((lang) => {
                    if (!langSearch) return true
                    const q = langSearch.toLowerCase()
                    return lang.name.toLowerCase().includes(q) || lang.id.toLowerCase().includes(q)
                  })
                  .map((lang) => (
                    <button
                      key={lang.id}
                      className={`code-language-option ${lang.id === language ? 'is-active' : ''}`}
                      onClick={() => {
                        updateAttributes({ language: lang.id })
                        setIsMenuOpen(false)
                        setLangSearch('')
                      }}
                      type="button"
                    >
                      {lang.name}
                    </button>
                  ))}
              </div>
            </div>
          )}
        </div>
        <div className="code-block-actions-right">
          <button
            className="code-block-toolbar-btn"
            onClick={(e) => { e.stopPropagation(); updateAttributes({ wrap: !isWrapped }) }}
            title={isWrapped ? 'Disable wrapping' : 'Enable wrapping'}
            type="button"
          >
            {isWrapped ? 'Unwrap' : 'Wrap'}
          </button>
          <button
            className="code-block-toolbar-btn"
            onClick={(e) => { e.stopPropagation(); void navigator.clipboard.writeText(node.textContent) }}
            title="Copy code"
            type="button"
          >
            Copy
          </button>
        </div>
      </div>
      <pre data-wrap={isWrapped ? 'true' : 'false'}>
        <NodeViewContent as={"code" as any} className={`language-${language}`} />
      </pre>
    </NodeViewWrapper>
  )
}

const EdenCodeBlock = CodeBlockLowlight.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      wrap: {
        default: true,
        parseHTML: (element: HTMLElement) => element.getAttribute('data-wrap') !== 'false',
        renderHTML: (attributes: { wrap?: boolean }) => ({
          'data-wrap': attributes.wrap === false ? 'false' : 'true',
        }),
      },
    }
  },
  addNodeView() {
    return ReactNodeViewRenderer(CodeBlockView)
  },
})

interface EditorProps {
  entry: Entry;
  allEntries: Entry[];
  noteTypes: NoteType[];
  codeToolsSettings: CodeToolsSettings | null;
  onSave: (entry: Entry) => Promise<SaveEntryResult | null>;
  onNavigate: (entryId: string) => void;
}

export default function Editor({ entry, allEntries, noteTypes, codeToolsSettings, onSave, onNavigate }: EditorProps) {
  const [title, setTitle] = useState(entry.title)
  const [noteTypeId, setNoteTypeId] = useState(entry.type_id)
  const [headerLayout, setHeaderLayout] = useState(entry.header_layout)
  const [headerProps, setHeaderProps] = useState<Record<string, unknown>>(() => safeParseHeaderProps(null, entry.header_props_json))
  const [saveConflict, setSaveConflict] = useState<string | null>(null)
  const [headerValidationError, setHeaderValidationError] = useState<string | null>(null)
  const [isNoteTypeMenuOpen, setIsNoteTypeMenuOpen] = useState(false)
  const [, setLintResultsByPos] = useState<Record<number, CodeLintDiagnostic[]>>({})
  const allEntriesRef = useRef(allEntries)
  const editorContentAreaRef = useRef<HTMLDivElement | null>(null)
  const noteTypeMenuRef = useRef<HTMLDivElement | null>(null)
  const lintRunIdRef = useRef(0)
  const lastSavedSnapshotRef = useRef('')
  const saveRunIdRef = useRef(0)
  const activeNoteType = useMemo(() => noteTypes.find(noteType => noteType.id === noteTypeId) ?? null, [noteTypeId, noteTypes])

  useEffect(() => {
    allEntriesRef.current = allEntries
  }, [allEntries])

  useEffect(() => {
    if (!isNoteTypeMenuOpen) {
      return
    }

    const handlePointerDown = (event: MouseEvent) => {
      if (noteTypeMenuRef.current?.contains(event.target as Node)) {
        return
      }

      setIsNoteTypeMenuOpen(false)
    }

    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setIsNoteTypeMenuOpen(false)
      }
    }

    window.addEventListener('mousedown', handlePointerDown)
    window.addEventListener('keydown', handleEscape)

    return () => {
      window.removeEventListener('mousedown', handlePointerDown)
      window.removeEventListener('keydown', handleEscape)
    }
  }, [isNoteTypeMenuOpen])

  const extensions = useMemo(() => [
    StarterKit.configure({
      codeBlock: false,
    }),
    Markdown,
    Placeholder.configure({
      placeholder: 'Начни писать что-нибудь интересное...',
    }),
    EdenCodeBlock.configure({
      lowlight,
      enableTabIndentation: true,
      tabSize: 4,
      defaultLanguage: null,
    }),
    Typography,
    Wikilink.configure({
      suggestion: {
        items: ({ query }: { query: string }) => {
          return allEntriesRef.current
            .filter(item => item.title.toLowerCase().includes(query.toLowerCase()))
            .slice(0, 10)
        },
        render: () => {
          let component: ReactRenderer<WikilinkListRef, any>;
          let popup: Instance[];

          return {
            onStart: (props: any) => {
              component = new ReactRenderer(WikilinkList, {
                props,
                editor: props.editor,
              })

              if (!props.clientRect) {
                return
              }

              popup = tippy('body', {
                getReferenceClientRect: props.clientRect,
                appendTo: () => document.body,
                content: component.element,
                showOnCreate: true,
                interactive: true,
                trigger: 'manual',
                placement: 'bottom-start',
              })
            },

            onUpdate(props: any) {
              component.updateProps(props)

              if (!props.clientRect) {
                return
              }

              popup[0].setProps({
                getReferenceClientRect: props.clientRect,
              })
            },

            onKeyDown(props: any) {
              if (props.event.key === 'Escape') {
                popup[0].hide()
                return true
              }
              return component.ref?.onKeyDown(props) || false
            },

            onExit() {
              popup[0].destroy()
              component.destroy()
            },
          }
        },
      },
    }),
    SlashCommand.configure({
      suggestion: {
        items: ({ query }: { query: string }) => {
          return [
            {
              title: 'Заголовок 1',
              description: 'Большой заголовок раздела',
              icon: 'H1',
              command: ({ editor, range }: { editor: TiptapEditor; range: Range }) => {
                editor.chain().focus().deleteRange(range).setNode('heading', { level: 1 }).run()
              },
            },
            {
              title: 'Заголовок 2',
              description: 'Средний заголовок',
              icon: 'H2',
              command: ({ editor, range }: { editor: TiptapEditor; range: Range }) => {
                editor.chain().focus().deleteRange(range).setNode('heading', { level: 2 }).run()
              },
            },
            {
              title: 'Текст',
              description: 'Обычный абзац',
              icon: 'P',
              command: ({ editor, range }: { editor: TiptapEditor; range: Range }) => {
                editor.chain().focus().deleteRange(range).setNode('paragraph').run()
              },
            },
            {
              title: 'Список',
              description: 'Маркированный список',
              icon: '•',
              command: ({ editor, range }: { editor: TiptapEditor; range: Range }) => {
                editor.chain().focus().deleteRange(range).toggleBulletList().run()
              },
            },
            {
              title: 'Код',
              description: 'Блок кода с подсветкой',
              icon: '{}',
              command: ({ editor, range }: { editor: TiptapEditor; range: Range }) => {
                editor.chain().focus().deleteRange(range).toggleCodeBlock().run()
              },
            },
            {
              title: 'Цитата',
              description: 'Блок цитирования',
              icon: '"',
              command: ({ editor, range }: { editor: TiptapEditor; range: Range }) => {
                editor.chain().focus().deleteRange(range).toggleBlockquote().run()
              },
            },
          ].filter(item => item.title.toLowerCase().includes(query.toLowerCase()))
        },
        render: () => {
          let component: ReactRenderer<SlashCommandListRef, any>;
          let popup: Instance[];

          return {
            onStart: (props: any) => {
              component = new ReactRenderer(SlashCommandList, {
                props,
                editor: props.editor,
              })

              if (!props.clientRect) {
                return
              }

              popup = tippy('body', {
                getReferenceClientRect: props.clientRect,
                appendTo: () => document.body,
                content: component.element,
                showOnCreate: true,
                interactive: true,
                trigger: 'manual',
                placement: 'bottom-start',
              })
            },

            onUpdate(props: any) {
              component.updateProps(props)

              if (!props.clientRect) {
                return
              }

              popup[0].setProps({
                getReferenceClientRect: props.clientRect,
              })
            },

            onKeyDown(props: any) {
              if (props.event.key === 'Escape') {
                popup[0].hide()
                return true
              }
              return component.ref?.onKeyDown(props) || false
            },

            onExit() {
              popup[0].destroy()
              component.destroy()
            },
          }
        },
      },
    }),
  ], [])

  const editor = useEditor({
    extensions,
    content: (() => {
      try {
        return entry.content_json ? JSON.parse(entry.content_json) : { type: 'doc', content: [{ type: 'paragraph' }] };
      } catch {
        return { type: 'doc', content: [{ type: 'paragraph' }] };
      }
    })(),
    autofocus: 'end',
    editable: true,
  })

  const applyCodeBlockText = useCallback((nodePos: number, nextCode: string) => {
    if (!editor) {
      return false
    }

    const codeBlockNode = editor.state.doc.nodeAt(nodePos)
    if (!codeBlockNode) {
      return false
    }

    const contentFrom = nodePos + 1
    const contentTo = nodePos + codeBlockNode.nodeSize - 1
    const transaction = editor.state.tr

    if (contentTo > contentFrom) {
      transaction.delete(contentFrom, contentTo)
    }

    if (nextCode.length > 0) {
      transaction.insertText(nextCode, contentFrom)
    }

    editor.view.dispatch(transaction)
    return true
  }, [editor])

  const formatAllCodeBlocks = useCallback(async () => {
    if (!editor || !codeToolsSettings) {
      return
    }

    const codeBlocks: Array<{ nodePos: number; code: string; language: string }> = []

    editor.state.doc.descendants((node, position) => {
      if (node.type.name === 'codeBlock') {
        codeBlocks.push({
          nodePos: position,
          code: node.textContent,
          language: resolveLanguageId((node.attrs as { language?: string | null }).language),
        })
      }

      return true
    })

    for (const block of [...codeBlocks].reverse()) {
      const result = await window.api.formatCodeBlock(block.language, block.code)
      if (result.code !== block.code) {
        applyCodeBlockText(block.nodePos, result.code)
      }
    }
  }, [applyCodeBlockText, codeToolsSettings, editor])

  const lintAllCodeBlocks = useCallback(async () => {
    if (!editor || !codeToolsSettings) {
      return
    }

    const runId = ++lintRunIdRef.current
    const codeBlocks: Array<{ nodePos: number; code: string; language: string }> = []

    editor.state.doc.descendants((node, position) => {
      if (node.type.name === 'codeBlock') {
        codeBlocks.push({
          nodePos: position,
          code: node.textContent,
          language: resolveLanguageId((node.attrs as { language?: string | null }).language),
        })
      }

      return true
    })

    const nextResults: Record<number, CodeLintDiagnostic[]> = {}

    for (const block of codeBlocks) {
      const result = await window.api.lintCodeBlock(block.language, block.code)
      if (!result.ok || result.diagnostics.length > 0) {
        nextResults[block.nodePos] = result.diagnostics
      }
    }

    if (runId !== lintRunIdRef.current) {
      return
    }

    setLintResultsByPos(nextResults)
  }, [codeToolsSettings, editor])

  useEffect(() => {
    if (!editor) return;

    try {
      const parsed = entry.content_json ? JSON.parse(entry.content_json) : { type: 'doc', content: [{ type: 'paragraph' }] };
      const currentContent = editor.getJSON();
      if (JSON.stringify(currentContent) !== JSON.stringify(parsed)) {
        editor.commands.setContent(parsed);
      }
    } catch (e) {
      console.error('Failed to parse content_json', e);
    }
  }, [editor, entry.content_json]);

  useEffect(() => {
    setLintResultsByPos({})
  }, [entry.id])

  useEffect(() => {
    setNoteTypeId(entry.type_id)
    setHeaderLayout(entry.header_layout)
    const nextNoteType = noteTypes.find(noteType => noteType.id === entry.type_id) ?? null
    setHeaderProps(safeParseHeaderProps(nextNoteType, entry.header_props_json))
    setHeaderValidationError(null)
  }, [entry.header_layout, entry.header_props_json, entry.id, entry.type_id, noteTypes])

  const getCurrentSnapshot = useCallback(() => {
    if (!editor) {
      return null
    }

    return JSON.stringify({
      title: title || 'Без названия',
      noteTypeId,
      headerLayout,
      headerProps,
      doc: editor.getJSON(),
      markdown: editor.getMarkdown(),
    })
  }, [editor, headerLayout, headerProps, noteTypeId, title])

  const handleNoteTypeChange = useCallback((nextTypeId: string) => {
    const nextNoteType = noteTypes.find(noteType => noteType.id === nextTypeId) ?? null
    setNoteTypeId(nextTypeId || null)
    setHeaderLayout(nextNoteType ? parseHeaderTemplate(nextNoteType.header_template_json).kind : null)
    setHeaderProps(createDefaultHeaderProps(nextNoteType))
    setHeaderValidationError(null)
    setIsNoteTypeMenuOpen(false)
  }, [noteTypes])

  const handleHeaderPropChange = useCallback((fieldId: string, value: unknown) => {
    setHeaderProps(currentProps => ({
      ...currentProps,
      [fieldId]: value,
    }))
  }, [])

  const save = useCallback(async () => {
    if (!editor) return

    const headerValidation = validateHeaderProps(activeNoteType, headerProps)
    if (!headerValidation.success) {
      setHeaderValidationError('Проверьте поля верхушки заметки')
      return
    }

    setHeaderValidationError(null)

    const snapshotBeforeSave = getCurrentSnapshot()
    if (!snapshotBeforeSave || lastSavedSnapshotRef.current === snapshotBeforeSave) {
      return
    }

    const saveRunId = ++saveRunIdRef.current

    if (codeToolsSettings?.formatOnSave) {
      await formatAllCodeBlocks()
    }

    if (codeToolsSettings?.lintTrigger === 'on_save') {
      await lintAllCodeBlocks()
    }

    const content_json = JSON.stringify(editor.getJSON())

    const saveResult = await onSave({
      ...entry,
      title: title || 'Без названия',
      content_json,
      type_id: noteTypeId,
      header_layout: headerLayout,
      header_props_json: JSON.stringify(headerValidation.data),
      schema_version: 1,
      updated_at: Date.now(),
    })

    if (!saveResult) {
      return
    }

    if (saveRunId !== saveRunIdRef.current) {
      return
    }

    if (!saveResult.ok && saveResult.reason === 'duplicate_title') {
      setSaveConflict('Заметка с таким названием уже есть в этой папке')
      return
    }

    if (!saveResult.ok && saveResult.reason === 'invalid_type_metadata') {
      setHeaderValidationError(saveResult.message)
      return
    }

    setSaveConflict(null)
    lastSavedSnapshotRef.current = getCurrentSnapshot() ?? snapshotBeforeSave
  }, [activeNoteType, codeToolsSettings?.formatOnSave, codeToolsSettings?.lintTrigger, editor, entry, formatAllCodeBlocks, getCurrentSnapshot, headerLayout, headerProps, lintAllCodeBlocks, noteTypeId, onSave, title])

  useEffect(() => {
    if (saveConflict) {
      setSaveConflict(null)
    }
  }, [title])

  useEffect(() => {
    setSaveConflict(null)
  }, [entry.id])

  useEffect(() => {
    if (!editor) return

    lastSavedSnapshotRef.current = getCurrentSnapshot() ?? ''
  }, [editor, entry.id, entry.updated_at, getCurrentSnapshot])

  useEffect(() => {
    if (!editor) return

    const handleEditorClick = (event: MouseEvent) => {
      const target = event.target as HTMLElement
      const wikilink = target.closest('span[data-id]')
      if (wikilink) {
        const entryId = wikilink.getAttribute('data-id')
        if (entryId) {
          onNavigate(entryId)
        }
      }
    }

    const editorView = editor.view.dom
    editorView.addEventListener('click', handleEditorClick)
    return () => editorView.removeEventListener('click', handleEditorClick)
  }, [editor, onNavigate])

  useEffect(() => {
    if (!editor) return

    const timer = setTimeout(() => {
      void save();
    }, 800);

    return () => clearTimeout(timer);
  }, [editor?.state.doc, title, save])

  useEffect(() => {
    if (!editor || codeToolsSettings?.lintTrigger !== 'on_idle') return

    const timer = window.setTimeout(() => {
      void lintAllCodeBlocks()
    }, 1000)

    return () => window.clearTimeout(timer)
  }, [codeToolsSettings?.lintTrigger, editor?.state.doc, lintAllCodeBlocks])

  useEffect(() => {
    if (!editor) return

    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 's') {
        e.preventDefault()
        void save()
      }
    }

    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [editor, save])

  return (
    <div
      className="editor-wrapper"
    >
      <div className="editor-header">
        <div className="editor-rail editor-header-rail">
          <div className="editor-header-main">
            <TypedHeader
              activeNoteType={activeNoteType}
              title={title}
              headerProps={headerProps}
              validationError={headerValidationError}
              onHeaderPropChange={handleHeaderPropChange}
            />
            <input
              className="title-input"
              value={title}
              onChange={e => setTitle(e.target.value)}
              placeholder="Заголовок"
            />
            <div className="note-type-inline" ref={noteTypeMenuRef}>
              <button
                className="note-type-trigger"
                data-testid="typed-note-trigger"
                onClick={() => setIsNoteTypeMenuOpen((current) => !current)}
                style={{ '--note-type-accent': activeNoteType?.color ?? 'var(--text-tertiary)' } as CSSProperties}
                type="button"
              >
                {activeNoteType?.name ?? 'Обычная заметка'}
              </button>
              {isNoteTypeMenuOpen && (
                <div className="note-type-menu" data-testid="typed-note-menu">
                  <button className={`note-type-menu-item ${noteTypeId ? '' : 'is-active'}`} onClick={() => handleNoteTypeChange('')} type="button">
                    Обычная заметка
                  </button>
                  {noteTypes.map((noteType) => (
                    <button
                      key={noteType.id}
                      className={`note-type-menu-item ${noteType.id === noteTypeId ? 'is-active' : ''}`}
                      onClick={() => handleNoteTypeChange(noteType.id)}
                      type="button"
                    >
                      {noteType.name}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
          <div className="editor-header-actions">
            {saveConflict && <span className="save-conflict-badge">{saveConflict}</span>}
          </div>
        </div>
      </div>
      <div
        ref={editorContentAreaRef}
        className="editor-content-area"
        onClick={() => {
          editor?.commands.focus()
        }}
      >
        <div className="editor-rail editor-content-rail">
          <EditorContent editor={editor} />
        </div>
      </div>
    </div>
  )
}
