// apps/eden/ts/src/SlashCommandList.vue
<template>
  <div class="slash-commands">
    <template v-if="items.length">
      <button
        v-for="(item, index) in items"
        :key="index"
        class="suggestion-item"
        :class="{ 'is-selected': index === selectedIndex }"
        @click="selectItem(index)"
      >
        <span class="command-icon">{{ item.icon }}</span>
        <div class="command-info">
          <span class="command-title">{{ item.title }}</span>
        </div>
      </button>
    </template>
    <div v-else class="suggestion-item no-result">Команд не найдено</div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import type { Editor, Range } from "@tiptap/vue-3";

export interface SlashCommandItem {
  title: string;
  description?: string;
  icon: string;
  command: (props: { editor: Editor; range: Range }) => void;
}

const props = defineProps<{
  items: SlashCommandItem[];
  command: (item: SlashCommandItem) => void;
}>();

const selectedIndex = ref(0);

watch(
  () => props.items,
  () => {
    selectedIndex.value = 0;
  },
);

function selectItem(index: number) {
  const item = props.items[index];
  if (item) props.command(item);
}

defineExpose({
  onKeyDown: ({ event }: { event: KeyboardEvent }): boolean => {
    if (event.key === "ArrowUp") {
      selectedIndex.value = (selectedIndex.value + props.items.length - 1) % props.items.length;
      return true;
    }
    if (event.key === "ArrowDown") {
      selectedIndex.value = (selectedIndex.value + 1) % props.items.length;
      return true;
    }
    if (event.key === "Enter") {
      selectItem(selectedIndex.value);
      return true;
    }
    return false;
  },
});
</script>

// apps/eden/ts/src/SlashCommandList.tsx
import { forwardRef, useEffect, useImperativeHandle, useState } from 'react'
import { Editor, Range } from '@tiptap/react'

interface SlashCommandItem {
  title: string;
  description: string;
  icon: string;
  command: (props: { editor: Editor; range: Range }) => void;
}

interface SlashCommandListProps {
  items: SlashCommandItem[];
  command: (item: SlashCommandItem) => void;
}

export interface SlashCommandListRef {
  onKeyDown: (props: { event: KeyboardEvent }) => boolean;
}

export const SlashCommandList = forwardRef<SlashCommandListRef, SlashCommandListProps>((props, ref) => {
  const [selectedIndex, setSelectedIndex] = useState(0)

  const selectItem = (index: number) => {
    const item = props.items[index]
    if (item) {
      props.command(item)
    }
  }

  useEffect(() => setSelectedIndex(0), [props.items])

  useImperativeHandle(ref, () => ({
    onKeyDown: ({ event }) => {
      if (event.key === 'ArrowUp') {
        setSelectedIndex((selectedIndex + props.items.length - 1) % props.items.length)
        return true
      }
      if (event.key === 'ArrowDown') {
        setSelectedIndex((selectedIndex + 1) % props.items.length)
        return true
      }
      if (event.key === 'Enter') {
        selectItem(selectedIndex)
        return true
      }
      return false
    },
  }))

  return (
    <div className="slash-commands">
      {props.items.length
        ? props.items.map((item, index: number) => (
          <button
            className={`suggestion-item ${index === selectedIndex ? 'is-selected' : ''}`}
            key={index}
            onClick={() => selectItem(index)}
          >
            <span className="command-icon">{item.icon}</span>
            <div className="command-info">
              <span className="command-title">{item.title}</span>
              <span className="command-description">{item.description}</span>
            </div>
          </button>
        ))
        : <div className="suggestion-item no-result">Команд не найдено</div>
      }
    </div>
  )
})

SlashCommandList.displayName = 'SlashCommandList'
