// products/eden/src/WikilinkList.vue
<template>
  <div class="wikilink-suggestions">
    <template v-if="items.length">
      <button
        v-for="(item, index) in items"
        :key="item.id"
        class="suggestion-item"
        :class="{ 'is-selected': index === selectedIndex }"
        @click="selectItem(index)"
      >
        {{ item.title }}
      </button>
    </template>
    <div v-else class="suggestion-item no-result">Ничего не найдено</div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";

const props = defineProps<{
  items: Array<{ id: string; title: string }>;
  command: (props: { id: string; label: string }) => void;
}>();

const selectedIndex = ref(0);

watch(
  () => props.items,
  () => {
    selectedIndex.value = 0;
  },
);

function selectItem(index: number) {
  const item = props.items[index];
  if (item) props.command({ id: item.id, label: item.title });
}

defineExpose({
  onKeyDown: ({ event }: { event: KeyboardEvent }): boolean => {
    if (event.key === "ArrowUp") {
      selectedIndex.value = (selectedIndex.value + props.items.length - 1) % props.items.length;
      return true;
    }
    if (event.key === "ArrowDown") {
      selectedIndex.value = (selectedIndex.value + 1) % props.items.length;
      return true;
    }
    if (event.key === "Enter") {
      selectItem(selectedIndex.value);
      return true;
    }
    return false;
  },
});
</script>

// apps/eden/ts/src/WikilinkList.tsx
import { forwardRef, useEffect, useImperativeHandle, useState } from 'react'

interface WikilinkListProps {
  items: Array<{ id: string; title: string }>;
  command: (props: { id: string; label: string }) => void;
}

export interface WikilinkListRef {
  onKeyDown: (props: { event: KeyboardEvent }) => boolean;
}

export const WikilinkList = forwardRef<WikilinkListRef, WikilinkListProps>((props, ref) => {
  const [selectedIndex, setSelectedIndex] = useState(0)

  const selectItem = (index: number) => {
    const item = props.items[index]
    if (item) {
      props.command({ id: item.id, label: item.title })
    }
  }

  const upHandler = () => {
    setSelectedIndex((selectedIndex + props.items.length - 1) % props.items.length)
  }

  const downHandler = () => {
    setSelectedIndex((selectedIndex + 1) % props.items.length)
  }

  const enterHandler = () => {
    selectItem(selectedIndex)
  }

  useEffect(() => setSelectedIndex(0), [props.items])

  useImperativeHandle(ref, () => ({
    onKeyDown: ({ event }) => {
      if (event.key === 'ArrowUp') {
        upHandler()
        return true
      }
      if (event.key === 'ArrowDown') {
        downHandler()
        return true
      }
      if (event.key === 'Enter') {
        enterHandler()
        return true
      }
      return false
    },
  }))

  return (
    <div className="wikilink-suggestions">
      {props.items.length
        ? props.items.map((item, index: number) => (
          <button
            className={`suggestion-item ${index === selectedIndex ? 'is-selected' : ''}`}
            key={item.id}
            onClick={() => selectItem(index)}
          >
            {item.title}
          </button>
        ))
        : <div className="suggestion-item no-result">Ничего не найдено</div>
      }
    </div>
  )
})

WikilinkList.displayName = 'WikilinkList'
