// apps/eden/ts/src/components/sidebar/SpaceRail.vue
<template>
  <aside class="spaces-rail" data-testid="spaces-rail">
    <div class="spaces-rail-list">
      <button
        v-for="space in spaces"
        :key="space.id"
        class="space-rail-item"
        :class="{ 'is-active': activeSpace === space.id }"
        :data-testid="`space-tab-${space.id}`"
        :title="space.label"
        type="button"
        @click="emit('selectSpace', space.id)"
      >
        <span aria-hidden="true" class="space-rail-badge">{{ space.icon }}</span>
      </button>
    </div>
  </aside>
</template>

<script setup vapor lang="ts">
import type { SpaceId } from "./types";

const spaces: Array<{ id: SpaceId; label: string; icon: string }> = [
  { id: "my-space", label: "Мое пространство", icon: "🏡" },
  { id: "all-objects", label: "Все объекты", icon: "📚" },
  { id: "all-notes", label: "Все заметки", icon: "📝" },
];

defineProps<{
  activeSpace: SpaceId;
}>();

const emit = defineEmits<{
  selectSpace: [spaceId: SpaceId];
}>();
</script>

// apps/eden/ts/src/components/sidebar/SpaceRail.tsx
export type SpaceId = 'my-space' | 'all-objects' | 'all-notes' | 'all-properties' | 'diary'

interface SpaceRailProps {
  activeSpace: SpaceId;
  onSelectSpace: (spaceId: SpaceId) => void;
}

const spaces: Array<{ id: SpaceId; label: string; icon: string }> = [
  { id: 'my-space', label: 'Мое пространство', icon: '🏡' },
  { id: 'all-objects', label: 'Все объекты', icon: '📚' },
  { id: 'all-notes', label: 'Все заметки', icon: '📝' },
]

export default function SpaceRail({
  activeSpace,
  onSelectSpace,
}: SpaceRailProps) {
  return (
    <aside className="spaces-rail" data-testid="spaces-rail">
      <div className="spaces-rail-list">
        {spaces.map((space) => (
          <button
            key={space.id}
            className={`space-rail-item ${activeSpace === space.id ? 'is-active' : ''}`}
            data-testid={`space-tab-${space.id}`}
            onClick={() => onSelectSpace(space.id)}
            title={space.label}
            type="button"
          >
            <span aria-hidden="true" className="space-rail-badge">{space.icon}</span>
          </button>
        ))}
      </div>
    </aside>
  )
}
