// apps/arrancador/src-vue/components/RawgMetadataPrompt.vue
<script setup lang="ts">
import { ExternalLink, Gamepad2, Loader2, Search, X } from "lucide-vue-next";
import { computed, onMounted, onUnmounted, shallowRef, watch } from "vue";
import { RouterLink } from "vue-router";
import { metadataApi } from "../../src/lib/api";
import type { Game, RawgGame } from "../../src/types";
import { useToast } from "../composables/useToast";

type GameLite = Pick<Game, "id" | "name">;

const props = defineProps<{
  game: GameLite;
  remaining: number;
}>();

const emit = defineEmits<{
  next: [];
  skipAll: [];
  afterApply: [];
}>();

const { notify } = useToast();

const query = shallowRef(props.game.name);
const results = shallowRef<RawgGame[]>([]);
const searching = shallowRef(false);
const applyingId = shallowRef<number | null>(null);
const renameFromMetadata = shallowRef(false);
const rawgKeyStatus = shallowRef<"unknown" | "present" | "missing">("unknown");
const panelRef = shallowRef<HTMLDivElement | null>(null);
const inputRef = shallowRef<HTMLInputElement | null>(null);

let searchSeq = 0;
let applySeq = 0;

const hasApiKey = computed(() => rawgKeyStatus.value === "present");

watch(
  () => props.game,
  async (game) => {
    query.value = game.name;
    results.value = [];
    searching.value = false;
    applyingId.value = null;
    rawgKeyStatus.value = "unknown";

    try {
      const key = await metadataApi.getApiKey();
      rawgKeyStatus.value = key?.trim() ? "present" : "missing";
    } catch {
      rawgKeyStatus.value = "missing";
    }
  },
  { immediate: true, deep: true },
);

watch(
  () => props.game.id,
  () => {
    if (hasApiKey.value && query.value.trim()) {
      void searchMetadata(query.value);
    }
  },
);

function getFocusableElements() {
  return Array.from(
    panelRef.value?.querySelectorAll<HTMLElement>(
      'button:not([disabled]), input:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])',
    ) ?? [],
  );
}

function onKeyDown(event: KeyboardEvent) {
  if (event.key === "Escape") {
    event.preventDefault();
    emit("next");
    return;
  }

  if (event.key !== "Tab") {
    return;
  }

  const focusables = getFocusableElements();
  if (focusables.length === 0) return;

  const currentIndex = focusables.indexOf(document.activeElement as HTMLElement);
  const nextIndex = event.shiftKey
    ? currentIndex <= 0
      ? focusables.length - 1
      : currentIndex - 1
    : currentIndex === focusables.length - 1
      ? 0
      : currentIndex + 1;

  event.preventDefault();
  focusables[nextIndex]?.focus();
}

async function searchMetadata(forcedQuery?: string) {
  const nextQuery = (forcedQuery ?? query.value).trim();
  if (!nextQuery) return;

  const seq = ++searchSeq;
  searching.value = true;

  try {
    const found = await metadataApi.search(nextQuery);
    if (searchSeq !== seq) return;
    results.value = found;

    if (found.length === 0) {
      notify({
        tone: "info",
        title: "Ничего не найдено",
        description: "Попробуйте уточнить запрос.",
        durationMs: 2600,
      });
    }
  } catch (cause) {
    if (searchSeq !== seq) return;
    console.error("RAWG search failed:", cause);
    notify({
      tone: "error",
      title: "Не удалось найти метаданные",
      description: "Проверьте RAWG API ключ в настройках.",
    });
  } finally {
    if (searchSeq === seq) {
      searching.value = false;
    }
  }
}

async function applyMetadata(rawgGame: RawgGame) {
  const seq = ++applySeq;
  applyingId.value = rawgGame.id;

  try {
    await metadataApi.apply(props.game.id, rawgGame.id, renameFromMetadata.value);
    if (applySeq !== seq) return;

    emit("afterApply");
    notify({
      tone: "success",
      title: "Метаданные применены",
      description: rawgGame.name,
      durationMs: 2400,
    });
    emit("next");
  } catch (cause) {
    if (applySeq !== seq) return;
    console.error("Failed to apply RAWG metadata:", cause);
    notify({
      tone: "error",
      title: "Не удалось применить метаданные",
    });
  } finally {
    if (applySeq === seq) {
      applyingId.value = null;
    }
  }
}

onMounted(() => {
  document.addEventListener("keydown", onKeyDown);
  window.setTimeout(() => inputRef.value?.focus(), 0);
});

onUnmounted(() => {
  document.removeEventListener("keydown", onKeyDown);
});
</script>

<template>
  <Teleport to="body">
    <div
      role="dialog"
      aria-modal="true"
      class="fixed inset-0 z-[120] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm"
      @mousedown.self="emit('next')"
    >
      <div
        ref="panelRef"
        class="relative flex max-h-[85vh] w-full max-w-xl flex-col overflow-hidden rounded-2xl border border-border/70 bg-card shadow-[0_30px_80px_rgba(0,0,0,0.45)]"
      >
        <div class="pointer-events-none absolute inset-0">
          <div
            class="absolute -top-24 -right-24 h-56 w-56 rounded-full blur-3xl opacity-60"
            style="background: radial-gradient(circle, rgba(56,189,248,0.22), rgba(56,189,248,0));"
          />
          <div
            class="absolute -bottom-24 -left-24 h-56 w-56 rounded-full blur-3xl opacity-50"
            style="background: radial-gradient(circle, rgba(244,63,94,0.18), rgba(244,63,94,0));"
          />
        </div>

        <div class="relative border-b border-border/70 p-4">
          <div class="flex items-start gap-3">
            <div class="min-w-0 flex-1">
              <div class="text-sm font-semibold">Добавить метаданные из RAWG</div>
              <div class="mt-0.5 truncate text-xs text-muted-foreground">
                {{ game.name }}
                <span v-if="remaining > 1"> · Осталось: {{ remaining }}</span>
              </div>
            </div>
            <button
              type="button"
              class="text-muted-foreground transition-colors hover:text-foreground"
              aria-label="Закрыть"
              @click="emit('skipAll')"
            >
              <X class="h-4 w-4" />
            </button>
          </div>
        </div>

        <div class="relative flex flex-1 flex-col overflow-hidden p-4">
          <div
            v-if="rawgKeyStatus === 'missing'"
            class="mb-4 rounded-xl border border-border/70 bg-secondary/20 p-3"
          >
            <div class="text-sm font-semibold">Нужен RAWG API ключ</div>
            <div class="mt-1 text-xs leading-relaxed text-muted-foreground">
              Добавьте ключ в настройках, чтобы искать метаданные.
            </div>
            <div class="mt-3 flex items-center justify-end gap-2">
              <button
                type="button"
                class="inline-flex h-9 items-center rounded-xl px-3 text-sm text-muted-foreground transition-colors hover:bg-accent/70 hover:text-foreground"
                @click="emit('next')"
              >
                Не сейчас
              </button>
              <RouterLink
                to="/settings"
                class="inline-flex h-9 items-center rounded-xl bg-primary px-3 text-sm font-[510] text-primary-foreground transition-colors hover:bg-accent hover:text-white"
              >
                Открыть настройки
              </RouterLink>
            </div>
          </div>

          <div class="mb-4 flex gap-2">
            <input
              ref="inputRef"
              v-model="query"
              placeholder="Название игры..."
              aria-label="Название игры"
              class="h-10 flex-1 rounded-xl border border-border/70 bg-background/60 px-3 text-sm outline-none"
              :disabled="!hasApiKey"
              @keydown.enter="void searchMetadata()"
            />
            <button
              type="button"
              class="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground transition-colors hover:bg-accent hover:text-white disabled:cursor-not-allowed disabled:opacity-60"
              :disabled="!hasApiKey || searching"
              @click="void searchMetadata()"
            >
              <Loader2 v-if="searching" class="h-4 w-4 animate-spin" />
              <Search v-else class="h-4 w-4" />
            </button>
          </div>

          <div class="mb-3 flex items-center justify-between gap-3 text-sm text-muted-foreground">
            <span id="rawg-rename-toggle">Использовать название из RAWG</span>
            <button
              type="button"
              class="inline-flex h-6 w-11 items-center rounded-full border border-border/70 px-1 transition-colors"
              :class="renameFromMetadata ? 'bg-primary/20' : 'bg-card/60'"
              aria-labelledby="rawg-rename-toggle"
              @click="renameFromMetadata = !renameFromMetadata"
            >
              <span
                class="h-4 w-4 rounded-full bg-white transition-transform"
                :class="renameFromMetadata ? 'translate-x-5' : 'translate-x-0'"
              />
            </button>
          </div>

          <div class="flex-1 overflow-y-auto">
            <div v-if="results.length > 0" class="space-y-2">
              <button
                v-for="result in results"
                :key="result.id"
                type="button"
                class="flex w-full items-center gap-3 rounded-xl border border-transparent p-3 text-left transition-colors hover:border-border hover:bg-secondary/70 disabled:cursor-not-allowed disabled:opacity-70"
                :disabled="applyingId !== null"
                @click="void applyMetadata(result)"
              >
                <img
                  v-if="result.background_image"
                  :src="result.background_image"
                  :alt="result.name"
                  class="h-14 w-14 rounded-lg border border-border/60 object-cover"
                  loading="lazy"
                  decoding="async"
                />
                <div
                  v-else
                  class="flex h-14 w-14 items-center justify-center rounded-lg border border-border/60 bg-muted"
                >
                  <Gamepad2 class="h-6 w-6 text-muted-foreground" />
                </div>

                <div class="min-w-0 flex-1">
                  <div class="truncate font-medium">{{ result.name }}</div>
                  <div class="mt-0.5 text-xs text-muted-foreground">
                    {{ result.released?.slice(0, 4) ?? "—" }}
                    <span v-if="result.metacritic != null"> · MC {{ result.metacritic }}</span>
                  </div>
                </div>

                <Loader2
                  v-if="applyingId === result.id"
                  class="h-4 w-4 animate-spin text-primary"
                />
                <ExternalLink v-else class="h-4 w-4 text-muted-foreground" />
              </button>
            </div>
            <div v-else class="py-10 text-center text-sm text-muted-foreground">
              {{
                hasApiKey
                  ? "Введите название и нажмите поиск"
                  : "Добавьте RAWG API ключ в настройках"
              }}
            </div>
          </div>
        </div>

        <div class="relative flex items-center justify-between gap-2 border-t border-border/70 p-4">
          <button
            type="button"
            class="inline-flex h-9 items-center rounded-xl px-3 text-sm text-muted-foreground transition-colors hover:bg-accent/70 hover:text-foreground"
            @click="emit('skipAll')"
          >
            Пропустить все
          </button>
          <button
            type="button"
            class="inline-flex h-9 items-center rounded-xl px-3 text-sm text-muted-foreground transition-colors hover:bg-accent/70 hover:text-foreground"
            @click="emit('next')"
          >
            Пропустить
          </button>
        </div>
      </div>
    </div>
  </Teleport>
</template>

// apps/arrancador/src/components/RawgMetadataPrompt.tsx
import { ExternalLink, Gamepad2, Loader2, Search, X } from "lucide-react";
import { useEffect, useId, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useToast } from "@/components/ToastProvider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Switch } from "@/components/ui/switch";
import { metadataApi } from "@/lib/api";
import type { Game, RawgGame } from "@/types";

type GameLite = Pick<Game, "id" | "name">;

interface RawgMetadataPromptProps {
  game: GameLite;
  remaining: number;
  onNext: () => void;
  onSkipAll: () => void;
  onAfterApply?: () => void | Promise<void>;
}

export function RawgMetadataPrompt({
  game,
  remaining,
  onNext,
  onSkipAll,
  onAfterApply,
}: RawgMetadataPromptProps) {
  const { notify } = useToast();

  const [query, setQuery] = useState(game.name);
  const [results, setResults] = useState<RawgGame[]>([]);
  const [searching, setSearching] = useState(false);
  const [applyingId, setApplyingId] = useState<number | null>(null);
  const [renameFromMetadata, setRenameFromMetadata] = useState(false);
  const [rawgKeyStatus, setRawgKeyStatus] = useState<
    "unknown" | "present" | "missing"
  >("unknown");

  const searchSeq = useRef(0);
  const applySeq = useRef(0);
  const panelRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const dialogId = useId();

  const hasApiKey = useMemo(() => rawgKeyStatus === "present", [rawgKeyStatus]);

  useEffect(() => {
    setQuery(game.name);
    setResults([]);
    setSearching(false);
    setApplyingId(null);

    let cancelled = false;
    setRawgKeyStatus("unknown");
    metadataApi
      .getApiKey()
      .then((key) => {
        if (cancelled) return;
        setRawgKeyStatus(key?.trim() ? "present" : "missing");
      })
      .catch(() => {
        if (cancelled) return;
        setRawgKeyStatus("missing");
      });

    return () => {
      cancelled = true;
    };
  }, [game.id, game.name]);

  useEffect(() => {
    if (!hasApiKey) return;
    if (!query.trim()) return;

    const timeout = window.setTimeout(() => {
      void searchMetadata(query);
    }, 80);

    return () => {
      window.clearTimeout(timeout);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [game.id, hasApiKey]);

  useEffect(() => {
    const handle = window.setTimeout(() => inputRef.current?.focus(), 0);
    return () => window.clearTimeout(handle);
  }, []);

  useEffect(() => {
    const getFocusableElements = () =>
      Array.from(
        panelRef.current?.querySelectorAll<HTMLElement>(
          'button:not([disabled]), input:not([disabled]), [href], [tabindex]:not([tabindex="-1"])',
        ) ?? [],
      );

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        event.preventDefault();
        onNext();
        return;
      }

      if (event.key !== "Tab") return;

      const focusables = getFocusableElements();
      if (focusables.length === 0) return;

      const currentIndex = focusables.indexOf(document.activeElement as HTMLElement);
      const nextIndex = event.shiftKey
        ? currentIndex <= 0
          ? focusables.length - 1
          : currentIndex - 1
        : currentIndex === focusables.length - 1
          ? 0
          : currentIndex + 1;

      event.preventDefault();
      focusables[nextIndex]?.focus();
    };

    document.addEventListener("keydown", onKeyDown);
    return () => document.removeEventListener("keydown", onKeyDown);
  }, [onNext]);

  const searchMetadata = async (forcedQuery?: string) => {
    const q = (forcedQuery ?? query).trim();
    if (!q) return;

    const seq = ++searchSeq.current;
    setSearching(true);
    try {
      const found = await metadataApi.search(q);
      if (searchSeq.current !== seq) return;
      setResults(found);
      if (found.length === 0) {
        notify({
          tone: "info",
          title: "Ничего не найдено",
          description: "Попробуйте уточнить запрос.",
          durationMs: 2600,
        });
      }
    } catch (error) {
      if (searchSeq.current !== seq) return;
      console.error("RAWG search failed:", error);
      notify({
        tone: "error",
        title: "Не удалось найти метаданные",
        description: "Проверьте RAWG API ключ в настройках.",
      });
    } finally {
      if (searchSeq.current === seq) {
        setSearching(false);
      }
    }
  };

  const applyMetadata = async (rawgGame: RawgGame) => {
    const seq = ++applySeq.current;
    setApplyingId(rawgGame.id);
    try {
      await metadataApi.apply(game.id, rawgGame.id, renameFromMetadata);
      if (applySeq.current !== seq) return;
      await onAfterApply?.();
      notify({
        tone: "success",
        title: "Метаданные применены",
        description: rawgGame.name,
        durationMs: 2400,
      });
      onNext();
    } catch (error) {
      if (applySeq.current !== seq) return;
      console.error("Failed to apply RAWG metadata:", error);
      notify({
        tone: "error",
        title: "Не удалось применить метаданные",
      });
    } finally {
      if (applySeq.current === seq) {
        setApplyingId(null);
      }
    }
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby={`${dialogId}-title`}
      aria-describedby={`${dialogId}-description`}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm animate-in fade-in duration-200"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) {
          onNext();
        }
      }}
    >
      <div
        ref={panelRef}
        className="relative flex w-full max-w-xl max-h-[85vh] flex-col overflow-hidden rounded-2xl border border-border/70 bg-card shadow-[0_30px_80px_rgba(0,0,0,0.45)]"
      >
        <div className="pointer-events-none absolute inset-0">
          <div
            className="absolute -top-24 -right-24 h-56 w-56 rounded-full blur-3xl opacity-60"
            style={{
              background:
                "radial-gradient(circle, rgba(56,189,248,0.22), rgba(56,189,248,0))",
            }}
          />
          <div
            className="absolute -bottom-24 -left-24 h-56 w-56 rounded-full blur-3xl opacity-50"
            style={{
              background:
                "radial-gradient(circle, rgba(244,63,94,0.18), rgba(244,63,94,0))",
            }}
          />
        </div>

        <div className="relative border-b border-border/70 p-4">
          <div className="flex items-start gap-3">
            <div className="min-w-0 flex-1">
              <div id={`${dialogId}-title`} className="text-sm font-semibold">
                Добавить метаданные из RAWG
              </div>
              <div
                id={`${dialogId}-description`}
                className="mt-0.5 truncate text-xs text-muted-foreground"
              >
                {game.name}
                {remaining > 1 ? ` · Осталось: ${remaining}` : ""}
              </div>
            </div>
            <button
              type="button"
              onClick={onSkipAll}
              className="text-muted-foreground transition-colors hover:text-foreground"
              aria-label="Закрыть"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        <div className="relative flex flex-1 flex-col overflow-hidden p-4">
          {rawgKeyStatus === "missing" && (
            <div className="mb-4 rounded-xl border border-border/70 bg-secondary/20 p-3">
              <div className="text-sm font-semibold">Нужен RAWG API ключ</div>
              <div className="mt-1 text-xs leading-relaxed text-muted-foreground">
                Добавьте ключ в настройках, чтобы искать метаданные.
              </div>
              <div className="mt-3 flex items-center justify-end gap-2">
                <Button variant="ghost" onClick={onNext}>
                  Не сейчас
                </Button>
                <Button asChild>
                  <Link to="/settings">Открыть настройки</Link>
                </Button>
              </div>
            </div>
          )}

          <div className="mb-4 flex gap-2">
            <Input
              ref={inputRef}
              placeholder="Название игры..."
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              onKeyDown={(event) => event.key === "Enter" && void searchMetadata()}
              disabled={!hasApiKey}
              autoFocus
              aria-label="Название игры"
              className="h-10"
            />
            <Button
              onClick={() => void searchMetadata()}
              disabled={!hasApiKey || searching}
              title={hasApiKey ? "Найти" : "Нужен RAWG API ключ"}
            >
              {searching ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Search className="h-4 w-4" />
              )}
            </Button>
          </div>

          <div className="mb-3 flex items-center justify-between gap-3 text-sm text-muted-foreground">
            <span id="rawg-rename-toggle">Использовать название из RAWG</span>
            <Switch
              checked={renameFromMetadata}
              onCheckedChange={setRenameFromMetadata}
              aria-labelledby="rawg-rename-toggle"
            />
          </div>

          <ScrollArea className="flex-1">
            {results.length > 0 ? (
              <div className="space-y-2">
                {results.map((result) => (
                  <button
                    type="button"
                    key={result.id}
                    className="flex w-full items-center gap-3 rounded-xl border border-transparent p-3 text-left transition-colors hover:border-border hover:bg-secondary/70 disabled:cursor-not-allowed disabled:opacity-70"
                    onClick={() => void applyMetadata(result)}
                    disabled={applyingId !== null}
                  >
                    {result.background_image ? (
                      <img
                        src={result.background_image}
                        alt={result.name}
                        className="h-14 w-14 rounded-lg border border-border/60 object-cover"
                        loading="lazy"
                        decoding="async"
                      />
                    ) : (
                      <div className="flex h-14 w-14 items-center justify-center rounded-lg border border-border/60 bg-muted">
                        <Gamepad2 className="h-6 w-6 text-muted-foreground" />
                      </div>
                    )}

                    <div className="min-w-0 flex-1">
                      <div className="truncate font-medium">{result.name}</div>
                      <div className="mt-0.5 text-xs text-muted-foreground">
                        {result.released?.slice(0, 4) ?? "—"}
                        {result.metacritic != null ? ` · MC ${result.metacritic}` : ""}
                      </div>
                    </div>

                    {applyingId === result.id ? (
                      <Loader2 className="h-4 w-4 animate-spin text-primary" />
                    ) : (
                      <ExternalLink className="h-4 w-4 text-muted-foreground" />
                    )}
                  </button>
                ))}
              </div>
            ) : (
              <div className="py-10 text-center text-sm text-muted-foreground">
                {hasApiKey
                  ? "Введите название и нажмите поиск"
                  : "Добавьте RAWG API ключ в настройках"}
              </div>
            )}
          </ScrollArea>
        </div>

        <div className="relative flex items-center justify-between gap-2 border-t border-border/70 p-4">
          <Button variant="ghost" onClick={onSkipAll}>
            Пропустить все
          </Button>
          <div className="flex items-center gap-2">
            <Button variant="ghost" onClick={onNext}>
              Пропустить
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
