// packages/visuals/components/GamePosterCard.vue
<script setup lang="ts">
import { computed, type Component } from "vue";
import { gamePosterCardClasses } from "../patterns";

export interface GamePosterCardProps {
  to: string;
  title: string;
  eyebrow?: string | null;
  coverSrc?: string | null;
  className?: string;
  linkComponent?: string | Component;
  linkProps?: Record<string, unknown>;
}

const props = withDefaults(defineProps<GamePosterCardProps>(), {
  eyebrow: null,
  coverSrc: null,
  className: "",
  linkComponent: "a",
  linkProps: () => ({}),
});

const rootClassName = computed(() =>
  [gamePosterCardClasses.root, props.className].filter(Boolean).join(" "),
);

const linkAttrs = computed(() =>
  props.linkComponent === "a"
    ? {
        href: props.to,
        title: props.title,
        "aria-label": props.title,
      }
    : {
        to: props.to,
        title: props.title,
        "aria-label": props.title,
        ...props.linkProps,
      },
);
</script>

<template>
  <component :is="linkComponent" v-bind="linkAttrs" :class="rootClassName">
    <div :class="gamePosterCardClasses.media">
      <img
        v-if="coverSrc"
        :src="coverSrc"
        :alt="title"
        :class="gamePosterCardClasses.image"
        loading="lazy"
        decoding="async"
      />
      <div v-else :class="gamePosterCardClasses.placeholder">
        <slot name="placeholder" />
      </div>
      <div :class="gamePosterCardClasses.scrim" aria-hidden="true" />
      <div :class="gamePosterCardClasses.overlay" aria-hidden="true" />
    </div>

    <div :class="gamePosterCardClasses.content">
      <div v-if="eyebrow" :class="gamePosterCardClasses.eyebrow" style="color: #ffffff">
        {{ eyebrow }}
      </div>
      <div
        :class="gamePosterCardClasses.title"
        style="color: #ffffff; text-shadow: 0 1px 2px rgba(0, 0, 0, 0.38)"
      >
        {{ title }}
      </div>
    </div>
  </component>
</template>

// packages/kepler-visuals/react/GamePosterCard.tsx
import { createElement, type ElementType, type ReactNode } from "react";

import { gamePosterCardClasses } from "../patterns";

const eyebrowStyle = {
  color: "#ffffff",
} as const;

const titleStyle = {
  color: "#ffffff",
  textShadow: "0 1px 2px rgba(0,0,0,0.38)",
} as const;

export interface GamePosterCardProps {
  to: string;
  title: string;
  eyebrow?: string | null;
  coverSrc?: string | null;
  placeholder?: ReactNode;
  className?: string;
  LinkComponent?: ElementType;
}

function joinClasses(...classes: Array<string | undefined>) {
  return classes.filter(Boolean).join(" ");
}

export function GamePosterCard({
  to,
  title,
  eyebrow,
  coverSrc,
  placeholder,
  className,
  LinkComponent,
}: GamePosterCardProps) {
  const rootClassName = joinClasses(gamePosterCardClasses.root, className);
  const mediaContent = createElement(
    "div",
    { className: gamePosterCardClasses.media },
    coverSrc
      ? createElement("img", {
          src: coverSrc,
          alt: title,
          className: gamePosterCardClasses.image,
          loading: "lazy",
          decoding: "async",
        })
      : createElement(
          "div",
          { className: gamePosterCardClasses.placeholder },
          placeholder,
        ),
    createElement("div", {
      className: gamePosterCardClasses.scrim,
      "aria-hidden": "true",
    }),
    createElement("div", {
      className: gamePosterCardClasses.overlay,
      "aria-hidden": "true",
    }),
  );
  const content = [
    mediaContent,
    createElement(
      "div",
      { className: gamePosterCardClasses.content },
      eyebrow
        ? createElement(
            "div",
            { className: gamePosterCardClasses.eyebrow, style: eyebrowStyle },
            eyebrow,
          )
        : null,
      createElement(
        "div",
        { className: gamePosterCardClasses.title, style: titleStyle },
        title,
      ),
    ),
  ];

  if (LinkComponent) {
    return createElement(
      LinkComponent,
      {
        to,
        "aria-label": title,
        title,
        className: rootClassName,
      },
      ...content,
    );
  }

  return createElement(
    "a",
    {
      href: to,
      "aria-label": title,
      title,
      className: rootClassName,
    },
    ...content,
  );
}
