// products/delphi/src/App.vue
<script setup lang="ts">
/* eslint-disable no-console */
import { computed, onMounted, onUnmounted, shallowRef, watch } from "vue";
import { RouterView, useRoute, useRouter } from "vue-router";
import {
  fetchProjectsFromArk,
  fetchTasksFromArk,
  getArkApiKey,
  getArkUrl,
  setArkApiKey,
  setArkUrl,
} from "@/services/sync/ark-types";
import { parseConnectionString } from "@/services/sync/pairing";
import type { TodoItem } from "@/types/task";
import { useTodoStore } from "@/store/todos";
import {
  arkGetTask,
  DELPHI_TASK_OBJ_TYPE_ID,
  subscribeArkObjectChanges,
} from "@/lib/electron-api-shim";
import SideBar from "@/components/SideBar.vue";
import QuickEntry from "@/components/QuickEntry.vue";
import QuickSearch from "@/components/QuickSearch.vue";
import AuthOverlay from "@/components/AuthOverlay.vue";
import { useQuickEntry } from "@/composables/useQuickEntry";
import { DesktopChrome, TitlebarHistoryControls, type TitlebarPlatform } from "@kosmos/visuals";
import { useSidebarState } from "@/composables/useSidebarState";
import { arkStatus, connectionState } from "@/composables/useSyncState";

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

const store = useTodoStore();
const route = useRoute();
const router = useRouter();
const { show: showQuickEntry } = useQuickEntry();

const quickSearchOpen = shallowRef(false);
const { sidebarHidden } = useSidebarState();
const backStack = shallowRef<string[]>([]);
const forwardStack = shallowRef<string[]>([]);
const historyReady = shallowRef(false);
const suppressHistoryRecording = shallowRef(false);

type RouterHistoryStateLike = {
  back?: string | null;
  forward?: string | null;
};

function handleGlobalKeydown(e: KeyboardEvent) {
  if ((e.metaKey || e.ctrlKey) && e.code === "KeyK") {
    e.preventDefault();
    quickSearchOpen.value = !quickSearchOpen.value;
  }
}

// ---------------------------------------------------------------------------
// Connection state
// ---------------------------------------------------------------------------

const authRequired = shallowRef(false);
const authBusy = shallowRef(false);
const authError = shallowRef<string | null>(null);

const isElectron = typeof window !== "undefined" && !!window.electronAPI;

const chromePlatform = computed<TitlebarPlatform>(() => {
  if (navigator.platform.startsWith("Mac")) return "mac";
  if (navigator.platform.startsWith("Linux")) return "linux";
  return "windows";
});

const browserHistoryState = computed(() => {
  void route.fullPath;

  if (typeof window === "undefined") return undefined;

  return (window.history.state as RouterHistoryStateLike | null) ?? undefined;
});

const canExitSettingsViaBack = computed(() => route.path === "/settings");

const canGoBack = computed(() => {
  if (isElectron) return backStack.value.length > 0 || canExitSettingsViaBack.value;
  return Boolean(browserHistoryState.value?.back) || canExitSettingsViaBack.value;
});

const canGoForward = computed(() => {
  if (isElectron) return forwardStack.value.length > 0;
  return Boolean(browserHistoryState.value?.forward);
});

async function navigateBack() {
  if (isElectron) {
    const targetPath = backStack.value.at(-1);
    if (!targetPath) {
      if (!canExitSettingsViaBack.value) return;
      await router.push("/");
      return;
    }

    suppressHistoryRecording.value = true;
    backStack.value = backStack.value.slice(0, -1);
    forwardStack.value = [...forwardStack.value, route.fullPath];

    try {
      await router.push(targetPath);
    } finally {
      suppressHistoryRecording.value = false;
    }

    return;
  }

  if (!browserHistoryState.value?.back) {
    if (!canExitSettingsViaBack.value) return;
    await router.push("/");
    return;
  }
  router.back();
}

async function navigateForward() {
  if (isElectron) {
    const targetPath = forwardStack.value.at(-1);
    if (!targetPath) return;

    suppressHistoryRecording.value = true;
    forwardStack.value = forwardStack.value.slice(0, -1);
    backStack.value = [...backStack.value, route.fullPath];

    try {
      await router.push(targetPath);
    } finally {
      suppressHistoryRecording.value = false;
    }

    return;
  }

  if (!browserHistoryState.value?.forward) return;
  router.forward();
}

watch(
  () => route.fullPath,
  (nextPath, previousPath) => {
    if (!isElectron) return;

    if (!historyReady.value) {
      historyReady.value = true;
      return;
    }

    if (suppressHistoryRecording.value || !previousPath || nextPath === previousPath) {
      return;
    }

    backStack.value = [...backStack.value, previousPath];
    forwardStack.value = [];
  },
);

// ---------------------------------------------------------------------------
// Cleanup registry
// ---------------------------------------------------------------------------

let cleanupCommandListeners: (() => void) | null = null;

function setupCommandBusBridge() {
  if (!window.electronAPI?.on) return;

  const unsubCreate = window.electronAPI.on("delphi:cmd:task:create", () => {
    showQuickEntry();
  });

  const unsubToday = window.electronAPI.on("delphi:cmd:task:today", () => {
    if (route.path !== "/today") {
      void router.push("/today");
    }
  });

  cleanupCommandListeners = () => {
    unsubCreate?.();
    unsubToday?.();
  };
}

async function bootstrapWeb() {
  const url = getArkUrl();
  const key = getArkApiKey();

  if (!url || !key) {
    authRequired.value = true;
    authError.value = null;
    connectionState.value = "offline";
    store.setHydrated(true);
    return;
  }

  connectionState.value = "syncing";
  arkStatus.value = "connecting";
  authRequired.value = false;
  authError.value = null;
  store.setHydrated(false);

  try {
    const [tasks, projects] = await Promise.all([fetchTasksFromArk(), fetchProjectsFromArk()]);

    store.setTodos(tasks);
    store.setProjects(projects);
    store.setAreas([]);
    store.setTags([]);
    store.setHeadings([]);
    connectionState.value = "online";
    arkStatus.value = "connected";
  } catch (error) {
    authRequired.value = true;
    authError.value = error instanceof Error ? error.message : "Ошибка подключения";
    connectionState.value = "offline";
    arkStatus.value = "error";
  } finally {
    store.setHydrated(true);
  }
}

async function bootstrapElectron() {
  connectionState.value = "syncing";
  arkStatus.value = "connecting";
  store.setHydrated(false);
  store.setTodos([]);
  store.setProjects([]);
  store.setAreas([]);
  store.setTags([]);
  store.setHeadings([]);

  try {
    const todos = (await window.electronAPI?.invoke("ark:listDelphiTasks")) as TodoItem[] | null;
    store.setTodos(Array.isArray(todos) ? todos : []);
    connectionState.value = "offline";
    arkStatus.value = "connected";
  } catch (err) {
    console.warn("[App] Ark task load failed:", err);
    connectionState.value = "offline";
    arkStatus.value = "error";
  } finally {
    store.setHydrated(true);
  }
}

function handleReconnect() {
  if (!isElectron) {
    void bootstrapWeb();
  }
}

async function handleAuthSubmit(connectionCode: string) {
  const parsed = parseConnectionString(connectionCode);

  if (!parsed) {
    authError.value = "Неверный формат. Ожидается: ark://host:port?key=...";
    return;
  }

  authBusy.value = true;
  authError.value = null;

  try {
    setArkUrl(parsed.server_url);
    setArkApiKey(parsed.api_key);
    await bootstrapWeb();
  } finally {
    authBusy.value = false;
  }
}

// ---------------------------------------------------------------------------
// ARK live updates (cross-app: Eden /задача → Delphi UI без reload)
// ---------------------------------------------------------------------------
//
// Подписка на `object_upserted` / `object_deleted` для task_obj. Pattern B —
// renderer держит cache, ARK events его инвалидируют. См.
// `lib/electron-api-shim.ts → subscribeArkObjectChanges`.

let cleanupArkObjectListener: (() => void) | null = null;

function setupArkObjectListener() {
  cleanupArkObjectListener?.();
  cleanupArkObjectListener = subscribeArkObjectChanges(async (change) => {
    if (change.event === "object_upserted") {
      if (change.typeId !== DELPHI_TASK_OBJ_TYPE_ID) return;
      const todo = await arkGetTask(change.id);
      if (!todo) {
        // Объект помечен deleted или type mismatch — снимаем из кэша если был.
        if (store.todos.some((t) => t.id === change.id)) {
          store.removeTodoLocal(change.id);
        }
        return;
      }
      store.upsertTodo(todo);
      return;
    }
    // object_deleted: type_id отсутствует в payload — проверяем по cache.
    if (store.todos.some((t) => t.id === change.id)) {
      store.removeTodoLocal(change.id);
    }
  });
}

onMounted(async () => {
  window.addEventListener("keydown", handleGlobalKeydown);
  setupArkObjectListener();
  if (isElectron) {
    setupCommandBusBridge();
    await bootstrapElectron();
  } else {
    void bootstrapWeb();
  }
});

onUnmounted(() => {
  window.removeEventListener("keydown", handleGlobalKeydown);
  cleanupCommandListeners?.();
  cleanupArkObjectListener?.();
  cleanupArkObjectListener = null;
});
</script>

<template>
  <DesktopChrome appearance="settings" :platform="chromePlatform" class="h-screen w-screen">
    <template #titlebar-leading>
      <TitlebarHistoryControls
        :back-disabled="!canGoBack"
        :forward-disabled="!canGoForward"
        back-title="Назад"
        forward-title="Вперёд"
        @back="navigateBack"
        @forward="navigateForward"
      />
    </template>

    <template #sidebar>
      <SideBar :hidden="sidebarHidden" :show-toggle="false" :reserve-top-inset="false" />
    </template>

    <main class="relative flex min-h-0 min-w-0 flex-1 flex-col">
      <RouterView />
      <QuickEntry />
    </main>
  </DesktopChrome>

  <QuickSearch v-model:open="quickSearchOpen" />

  <AuthOverlay
    v-if="!isElectron && authRequired"
    :busy="authBusy"
    :error-message="authError"
    @submit="handleAuthSubmit"
  />
</template>

// apps/delphi/ts/src/App.tsx
import "./global.css";
import { useEffect, useState } from "react";
import AuthOverlay from "@/components/AuthOverlay";
import QuickEntry from "@/components/QuickEntry";
import QuickOpen from "@/components/QuickOpen";
import SideBar from "@/components/sideBar";
import AppRoutes from "@/routes";
import {
  type ArkChange,
  arkChangeToTodoItem,
  arkChangeToProject,
  arkChangeEventType,
  arkSync,
  getArkApiKey,
  getArkUrl,
  setArkApiKey,
  setArkUrl,
  fetchTasksFromArk,
  fetchProjectsFromArk,
} from "@/services/sync/ark-client";
import { parseConnectionString } from "@/services/sync/pairing";
import { setupMeshFromArkKey } from "@/services/sync/peer-bridge";
import useTodoStore from "@/store/todos";

type ConnectionState = "online" | "syncing" | "offline";

function ConnectionDot({ state }: { state: ConnectionState }) {
  const color =
    state === "online"
      ? "bg-emerald-500"
      : state === "syncing"
        ? "bg-amber-500 animate-pulse"
        : "bg-rose-500";
  const title =
    state === "online"
      ? "Подключено"
      : state === "syncing"
        ? "Подключение..."
        : "Нет связи";

  return (
    <div
      className={`fixed top-4 right-4 z-40 h-2.5 w-2.5 rounded-full ${color}`}
      title={title}
    />
  );
}

function App() {
  const setTodos = useTodoStore((s) => s.setTodos);
  const setProjects = useTodoStore((s) => s.setProjects);
  const upsertTodo = useTodoStore((s) => s.upsertTodo);
  const removeTodo = useTodoStore((s) => s.removeTodo);
  const upsertProject = useTodoStore((s) => s.upsertProject);
  const removeProject = useTodoStore((s) => s.removeProject);
  const setHydrated = useTodoStore((s) => s.setHydrated);
  const [authRequired, setAuthRequired] = useState(false);
  const [authBusy, setAuthBusy] = useState(false);
  const [authError, setAuthError] = useState<string | null>(null);
  const [bootstrapNonce, setBootstrapNonce] = useState(0);
  const [connectionState, setConnectionState] =
    useState<ConnectionState>("syncing");

  useEffect(() => {
    // Subscribe to sync changes BEFORE connecting so we don't miss initial sync_changes
    const unsubStatus = arkSync.onStatus((connected) => {
      setConnectionState(
        connected ? (arkSync.isSynced ? "online" : "syncing") : "offline",
      );
    });

    const unsubChange = arkSync.onChange((change) => {
      const eventType = arkChangeEventType(change);

      if (eventType === "project") {
        if (change.change_type === "delete") {
          removeProject(change.event_id);
          return;
        }
        const project = arkChangeToProject(change);
        if (project) upsertProject(project);
        return;
      }

      // Default: handle as task
      if (change.change_type === "delete") {
        removeTodo(change.event_id);
        return;
      }
      const todo = arkChangeToTodoItem(change);
      if (todo) upsertTodo(todo);
    });

    const url = getArkUrl();
    const key = getArkApiKey();

    if (!url || !key) {
      setAuthRequired(true);
      setConnectionState("offline");
      setHydrated(true);
      return () => {
        unsubStatus();
        unsubChange();
      };
    }

    // Load tasks and projects from Ark HTTP API
    Promise.all([fetchTasksFromArk(), fetchProjectsFromArk()])
      .then(([tasks, projects]) => {
        if (tasks.length > 0) setTodos(tasks);
        if (projects.length > 0) setProjects(projects);
      })
      .catch((err) => {
        console.warn("[App] Failed to bootstrap from Ark:", err);
      });

    // Connect WebSocket for realtime sync
    if (!arkSync.isConnected) {
      arkSync.connect(url, key);
    }
    setAuthRequired(false);
    setAuthError(null);
    setConnectionState("syncing");
    setHydrated(true);

    return () => {
      unsubStatus();
      unsubChange();
    };
  }, [
    bootstrapNonce,
    setHydrated,
    setTodos,
    upsertTodo,
    removeTodo,
    setProjects,
    upsertProject,
    removeProject,
  ]);

  // Listen for incoming P2P peer changes (Electron only)
  useEffect(() => {
    if (!window.electronAPI?.on) return;
    const cleanup = window.electronAPI.on("peer:change", (...args: unknown[]) => {
      const change = args[0] as ArkChange;
      if (!change || !change.event_id) return;

      const eventType = arkChangeEventType(change);

      if (eventType === "project") {
        if (change.change_type === "delete") {
          removeProject(change.event_id);
          return;
        }
        const project = arkChangeToProject(change);
        if (project) upsertProject(project);
        return;
      }

      // Default: handle as task
      if (change.change_type === "delete") {
        removeTodo(change.event_id);
        return;
      }
      const todo = arkChangeToTodoItem(change);
      if (todo) upsertTodo(todo);
    });
    return cleanup;
  }, [upsertTodo, removeTodo, upsertProject, removeProject]);

  // Auto-setup mesh credentials from existing Ark key (Electron only)
  useEffect(() => {
    const key = getArkApiKey();
    if (key) {
      setupMeshFromArkKey(key);
    }
  }, []);

  const handleAuthSubmit = async (connectionCode: string) => {
    const parsed = parseConnectionString(connectionCode);

    if (!parsed) {
      setAuthError("Неверный формат. Ожидается: ark://host:port?key=...");
      return;
    }

    setAuthBusy(true);
    setAuthError(null);
    setConnectionState("syncing");

    try {
      setArkUrl(parsed.server_url);
      setArkApiKey(parsed.api_key);
      arkSync.connect(parsed.server_url, parsed.api_key);
      setupMeshFromArkKey(parsed.api_key);
      setAuthRequired(false);
      setBootstrapNonce((value) => value + 1);
    } catch (error) {
      setAuthError(
        error instanceof Error ? error.message : "Ошибка подключения",
      );
      setConnectionState("offline");
    } finally {
      setAuthBusy(false);
    }
  };

  return (
    <>
      <ConnectionDot state={connectionState} />
      <main className="flex min-h-0 min-w-0 flex-1">
        <SideBar />
        <AppRoutes />
      </main>
      <QuickEntry />
      <QuickOpen />
      {authRequired ? (
        <AuthOverlay
          busy={authBusy}
          errorMessage={authError}
          onSubmit={handleAuthSubmit}
        />
      ) : null}
    </>
  );
}

export default App;
