// apps/delphi/ts/src/components/QuickEntry.tsx
import { Calendar, Folder, Moon, Star, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import useTodoStore from "@/store/todos";

export default function QuickEntry() {
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [notes, setNotes] = useState("");
  const [isToday, setIsToday] = useState(false);
  const [isEvening, setIsEvening] = useState(false);
  const [scheduledDate, setScheduledDate] = useState("");
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(
    null,
  );
  const [showProjectMenu, setShowProjectMenu] = useState(false);

  const titleRef = useRef<HTMLInputElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const projectMenuRef = useRef<HTMLDivElement>(null);

  const addTodo = useTodoStore((s) => s.addTodo);
  const projects = useTodoStore((s) => s.projects);

  const selectedProject = projects.find((p) => p.id === selectedProjectId);

  const reset = useCallback(() => {
    setTitle("");
    setNotes("");
    setIsToday(false);
    setIsEvening(false);
    setScheduledDate("");
    setSelectedProjectId(null);
    setShowProjectMenu(false);
  }, []);

  const close = useCallback(() => {
    setOpen(false);
    reset();
  }, [reset]);

  const save = useCallback(() => {
    const trimmed = title.trim();
    if (!trimmed) {
      close();
      return;
    }

    addTodo({
      title: trimmed,
      notes: notes || null,
      isToday,
      isEvening,
      scheduledDate: scheduledDate || null,
      projectId: selectedProjectId,
    });

    close();
  }, [
    title,
    notes,
    isToday,
    isEvening,
    scheduledDate,
    selectedProjectId,
    addTodo,
    close,
  ]);

  // Cmd+N to toggle
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.metaKey && e.key === "n" && !e.shiftKey && !e.altKey) {
        e.preventDefault();
        setOpen((prev) => {
          if (prev) {
            reset();
            return false;
          }
          return true;
        });
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [reset]);

  // Focus title when opened
  useEffect(() => {
    if (open) {
      requestAnimationFrame(() => titleRef.current?.focus());
    }
  }, [open]);

  // Close project menu on outside click
  useEffect(() => {
    if (!showProjectMenu) return;
    const handler = (e: MouseEvent) => {
      if (
        projectMenuRef.current &&
        !projectMenuRef.current.contains(e.target as Node)
      ) {
        setShowProjectMenu(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [showProjectMenu]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-[20vh]">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/40" onClick={close} />

      {/* Panel */}
      <div
        ref={panelRef}
        className="relative z-10 w-[480px] rounded-2xl border border-(--border) bg-(--popover) shadow-2xl"
      >
        <div className="flex flex-col gap-3 p-5">
          {/* Title */}
          <input
            ref={titleRef}
            type="text"
            placeholder="Новая задача"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                save();
              }
              if (e.key === "Escape") {
                e.preventDefault();
                close();
              }
            }}
            className="w-full text-lg font-semibold text-(--foreground) placeholder:text-(--muted-foreground)"
          />

          {/* Notes */}
          <textarea
            placeholder="Заметки"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            rows={2}
            onKeyDown={(e) => {
              if (e.key === "Escape") {
                e.preventDefault();
                close();
              }
            }}
            className="w-full resize-none text-sm text-(--muted-foreground) placeholder:text-(--muted-foreground)/60"
          />

          {/* Divider */}
          <div className="h-px bg-(--border) opacity-50" />

          {/* Metadata row */}
          <div className="flex flex-wrap items-center gap-2">
            {/* Schedule date */}
            <label className="flex cursor-pointer items-center gap-1.5 rounded-full bg-(--secondary) px-3 py-1.5 text-xs transition-colors hover:bg-(--accent)">
              <Calendar
                size={12}
                className={
                  scheduledDate ? "text-blue-500" : "text-(--muted-foreground)"
                }
              />
              <input
                type="date"
                value={scheduledDate}
                onChange={(e) => setScheduledDate(e.target.value)}
                className="w-[100px] cursor-pointer bg-transparent text-xs"
              />
            </label>

            {/* Today */}
            <button
              type="button"
              onClick={() => {
                setIsToday((prev) => !prev);
                if (!isToday) setIsEvening(false);
              }}
              className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs transition-colors ${
                isToday
                  ? "bg-yellow-500/15 text-yellow-500"
                  : "bg-(--secondary) text-(--muted-foreground) hover:bg-(--accent)"
              }`}
            >
              <Star size={12} />
              <span>Сегодня</span>
            </button>

            {/* Evening */}
            <button
              type="button"
              onClick={() => {
                setIsEvening((prev) => !prev);
                if (!isEvening) setIsToday(true);
              }}
              className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs transition-colors ${
                isEvening
                  ? "bg-indigo-500/15 text-indigo-400"
                  : "bg-(--secondary) text-(--muted-foreground) hover:bg-(--accent)"
              }`}
            >
              <Moon size={12} />
              <span>Вечер</span>
            </button>

            <div className="flex-1" />

            {/* Project picker */}
            <div className="relative" ref={projectMenuRef}>
              <button
                type="button"
                onClick={() => setShowProjectMenu((prev) => !prev)}
                className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs transition-colors ${
                  selectedProject
                    ? "bg-blue-500/15 text-blue-500"
                    : "bg-(--secondary) text-(--muted-foreground) hover:bg-(--accent)"
                }`}
              >
                <Folder size={12} />
                <span>{selectedProject?.title ?? "Входящие"}</span>
              </button>

              {showProjectMenu && (
                <div className="absolute right-0 top-full z-20 mt-1 min-w-[180px] rounded-lg border border-(--border) bg-(--popover) py-1 shadow-lg">
                  <button
                    type="button"
                    onClick={() => {
                      setSelectedProjectId(null);
                      setShowProjectMenu(false);
                    }}
                    className="w-full px-3 py-1.5 text-left text-xs text-(--foreground) hover:bg-(--accent)"
                  >
                    Входящие
                  </button>
                  {projects.map((project) => (
                    <button
                      key={project.id}
                      type="button"
                      onClick={() => {
                        setSelectedProjectId(project.id);
                        setShowProjectMenu(false);
                      }}
                      className="w-full px-3 py-1.5 text-left text-xs text-(--foreground) hover:bg-(--accent)"
                    >
                      {project.title}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Close button */}
        <button
          type="button"
          onClick={close}
          className="absolute right-3 top-3 rounded-md p-1 text-(--muted-foreground) hover:bg-(--accent) hover:text-(--foreground)"
        >
          <X size={14} />
        </button>
      </div>
    </div>
  );
}

// apps/delphi/ts/src/components/QuickEntry.vue
<script setup lang="ts">
import {
  shallowRef,
  useTemplateRef,
  onMounted,
  onUnmounted,
  nextTick,
  watch,
} from "vue";
import { Calendar, Folder, Moon, Star, X } from "lucide-vue-next";
import { useTodoStore } from "@/store/todos";
import { storeToRefs } from "pinia";
import { useQuickEntry } from "@/composables/useQuickEntry";

const { open, hide } = useQuickEntry();
const title = shallowRef("");
const notes = shallowRef("");
const isToday = shallowRef(false);
const isEvening = shallowRef(false);
const scheduledDate = shallowRef("");
const selectedProjectId = shallowRef<string | null>(null);
const showProjectMenu = shallowRef(false);

const titleRef = useTemplateRef<HTMLInputElement>("titleInput");
const projectMenuRef = useTemplateRef<HTMLDivElement>("projectMenu");

const store = useTodoStore();
const { projects } = storeToRefs(store);

const selectedProject = () =>
  projects.value.find((p) => p.id === selectedProjectId.value);

function reset() {
  title.value = "";
  notes.value = "";
  isToday.value = false;
  isEvening.value = false;
  scheduledDate.value = "";
  selectedProjectId.value = null;
  showProjectMenu.value = false;
}

function close() {
  hide();
  reset();
}

function save() {
  const trimmed = title.value.trim();
  if (!trimmed) {
    close();
    return;
  }

  store.addTodo({
    title: trimmed,
    notes: notes.value || null,
    isToday: isToday.value,
    isEvening: isEvening.value,
    scheduledDate: scheduledDate.value || null,
    projectId: selectedProjectId.value,
  });

  close();
}

function onTitleKeyDown(e: KeyboardEvent) {
  if (e.key === "Enter") {
    e.preventDefault();
    save();
  }
  if (e.key === "Escape") {
    e.preventDefault();
    close();
  }
}

function onNotesKeyDown(e: KeyboardEvent) {
  if (e.key === "Escape") {
    e.preventDefault();
    close();
  }
}

function toggleToday() {
  const prev = isToday.value;
  isToday.value = !prev;
  if (!prev) isEvening.value = false;
}

function toggleEvening() {
  const prev = isEvening.value;
  isEvening.value = !prev;
  if (!prev) isToday.value = true;
}

// Cmd+N to toggle
onMounted(() => {
  const handler = (e: KeyboardEvent) => {
    if (e.metaKey && e.key === "n" && !e.shiftKey && !e.altKey) {
      e.preventDefault();
      if (open.value) {
        close();
      } else {
        open.value = true;
      }
    }
  };
  window.addEventListener("keydown", handler);
  onUnmounted(() => window.removeEventListener("keydown", handler));
});

// Focus title when opened
watch(open, (val) => {
  if (val) {
    nextTick(() => titleRef.value?.focus());
  }
});

// Close project menu on outside click
watch(showProjectMenu, (val) => {
  if (!val) return;
  const handler = (e: MouseEvent) => {
    if (
      projectMenuRef.value &&
      !projectMenuRef.value.contains(e.target as Node)
    ) {
      showProjectMenu.value = false;
    }
  };
  document.addEventListener("mousedown", handler);
  // Use a watch cleanup to remove the listener
  const cleanup = () => document.removeEventListener("mousedown", handler);
  onUnmounted(cleanup);
  watch(
    showProjectMenu,
    (newVal) => {
      if (!newVal) cleanup();
    },
    { once: true },
  );
});
</script>

<template>
  <div
    v-if="open"
    class="fixed inset-0 z-50 flex items-start justify-center pt-[20vh]"
  >
    <!-- Backdrop -->
    <div class="absolute inset-0 bg-black/40" @click="close" />

    <!-- Panel -->
    <div
      class="relative z-10 w-[480px] rounded-2xl border border-(--border) bg-(--popover) shadow-2xl"
    >
      <div class="flex flex-col gap-3 p-5">
        <!-- Title -->
        <input
          ref="titleInput"
          type="text"
          placeholder="Новая задача"
          :value="title"
          class="w-full text-lg font-semibold text-(--foreground) placeholder:text-(--muted-foreground)"
          @input="title = ($event.target as HTMLInputElement).value"
          @keydown="onTitleKeyDown"
        />

        <!-- Notes -->
        <textarea
          placeholder="Заметки"
          :value="notes"
          :rows="2"
          class="w-full resize-none text-sm text-(--muted-foreground) placeholder:text-(--muted-foreground)/60"
          @input="notes = ($event.target as HTMLTextAreaElement).value"
          @keydown="onNotesKeyDown"
        />

        <!-- Divider -->
        <div class="h-px bg-(--border) opacity-50" />

        <!-- Metadata row -->
        <div class="flex flex-wrap items-center gap-2">
          <!-- Schedule date -->
          <label
            class="flex cursor-pointer items-center gap-1.5 rounded-full bg-(--secondary) px-3 py-1.5 text-xs transition-colors hover:bg-(--accent)"
          >
            <Calendar
              :size="12"
              :class="
                scheduledDate ? 'text-blue-500' : 'text-(--muted-foreground)'
              "
            />
            <input
              type="date"
              :value="scheduledDate"
              class="w-[100px] cursor-pointer bg-transparent text-xs"
              @input="scheduledDate = ($event.target as HTMLInputElement).value"
            />
          </label>

          <!-- Today -->
          <button
            type="button"
            :class="[
              'flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs transition-colors',
              isToday
                ? 'bg-yellow-500/15 text-yellow-500'
                : 'bg-(--secondary) text-(--muted-foreground) hover:bg-(--accent)',
            ]"
            @click="toggleToday"
          >
            <Star :size="12" />
            <span>Сегодня</span>
          </button>

          <!-- Evening -->
          <button
            type="button"
            :class="[
              'flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs transition-colors',
              isEvening
                ? 'bg-indigo-500/15 text-indigo-400'
                : 'bg-(--secondary) text-(--muted-foreground) hover:bg-(--accent)',
            ]"
            @click="toggleEvening"
          >
            <Moon :size="12" />
            <span>Вечер</span>
          </button>

          <div class="flex-1" />

          <!-- Project picker -->
          <div ref="projectMenu" class="relative">
            <button
              type="button"
              :class="[
                'flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs transition-colors',
                selectedProject()
                  ? 'bg-blue-500/15 text-blue-500'
                  : 'bg-(--secondary) text-(--muted-foreground) hover:bg-(--accent)',
              ]"
              @click="showProjectMenu = !showProjectMenu"
            >
              <Folder :size="12" />
              <span>{{ selectedProject()?.title ?? "Входящие" }}</span>
            </button>

            <div
              v-if="showProjectMenu"
              class="absolute right-0 top-full z-20 mt-1 min-w-[180px] rounded-lg border border-(--border) bg-(--popover) py-1 shadow-lg"
            >
              <button
                type="button"
                class="w-full px-3 py-1.5 text-left text-xs text-(--foreground) hover:bg-(--accent)"
                @click="
                  selectedProjectId = null;
                  showProjectMenu = false;
                "
              >
                Входящие
              </button>
              <button
                v-for="project in projects"
                :key="project.id"
                type="button"
                class="w-full px-3 py-1.5 text-left text-xs text-(--foreground) hover:bg-(--accent)"
                @click="
                  selectedProjectId = project.id;
                  showProjectMenu = false;
                "
              >
                {{ project.title }}
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Close button -->
      <button
        type="button"
        class="absolute right-3 top-3 rounded-md p-1 text-(--muted-foreground) hover:bg-(--accent) hover:text-(--foreground)"
        @click="close"
      >
        <X :size="14" />
      </button>
    </div>
  </div>
</template>
