// packages/kepler-visuals/components/Sidebar.vue
<script setup lang="ts">
import type { Component } from "vue";
import { computed } from "vue";
import { RouterLink } from "vue-router";
import { PanelLeftClose } from "lucide-vue-next";
import ResizableSidebar, {
  type SidebarConfig,
} from "./ResizableSidebar.vue";
import SidebarButton from "./SidebarButton.vue";

export interface SidebarNavItem {
  id: string;
  icon: Component;
  to?: string;
  label?: string;
}

export interface SidebarProjectItem {
  id: string;
  label: string;
  to: string;
  active?: boolean;
  colorClass?: string;
}

interface Props {
  primaryItems: SidebarNavItem[];
  projectItems?: SidebarProjectItem[];
  projectSectionLabel?: string;
  footerItems?: SidebarNavItem[];
  isMac?: boolean;
  toggleTitle?: string;
  defaultWidth?: number;
  minWidth?: number;
  maxWidth?: number;
  hiddenWidth?: number;
  toggleShortcut?: string;
  dragRegion?: boolean;
  initialConfig?: Partial<SidebarConfig>;
}

const props = withDefaults(defineProps<Props>(), {
  projectItems: () => [],
  projectSectionLabel: "Проекты",
  footerItems: () => [],
  isMac: false,
  toggleTitle: "Скрыть сайдбар (⌘B)",
  defaultWidth: 200,
  minWidth: 160,
  maxWidth: 320,
  hiddenWidth: 80,
  toggleShortcut: undefined,
  dragRegion: false,
  initialConfig: undefined,
});

const emit = defineEmits<{
  configChange: [config: SidebarConfig];
}>();

const hasProjects = computed(() => props.projectItems.length > 0);
</script>

<template>
  <ResizableSidebar
    :default-width="defaultWidth"
    :min-width="minWidth"
    :max-width="maxWidth"
    :hidden-width="hiddenWidth"
    :toggle-shortcut="toggleShortcut"
    :drag-region="dragRegion"
    :initial-config="initialConfig"
    @config-change="emit('configChange', $event)"
  >
    <template #default="{ toggle }">
      <aside class="kepler-sidebar-shell flex min-h-0 h-full flex-col justify-between p-2">
        <div v-if="isMac" class="flex items-center justify-end pb-3">
          <button
            type="button"
            class="kepler-sidebar-top-toggle rounded-lg p-1.5 text-white/40 transition-colors hover:bg-white/6 hover:text-white"
            :title="toggleTitle"
            @click="toggle"
          >
            <PanelLeftClose :size="16" />
          </button>
        </div>

        <div class="flex flex-1 flex-col overflow-y-auto gap-0.5">
          <SidebarButton
            v-for="item in primaryItems"
            :key="item.id"
            :icon="item.icon"
            :to="item.to"
            :label="item.label"
          />

          <template v-if="hasProjects">
            <div class="my-2 border-t border-(--border)" />
            <div
              class="px-3 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-wider text-(--muted-foreground)/60 select-none"
            >
              {{ projectSectionLabel }}
            </div>
            <RouterLink
              v-for="project in projectItems"
              :key="project.id"
              :to="project.to"
              :class="[
                'kepler-sidebar-project-link flex h-10 w-full cursor-pointer items-center gap-2.5 px-3 py-2 text-sm transition-colors',
                project.active
                  ? 'bg-(--surface) text-(--foreground) font-medium'
                  : 'text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)',
              ]"
            >
              <span
                :class="[
                  'kepler-sidebar-project-dot block h-2.5 w-2.5 shrink-0 rounded-full',
                  project.colorClass ?? 'bg-(--muted-foreground)',
                ]"
              />
              <span class="truncate select-none">{{ project.label }}</span>
            </RouterLink>
          </template>
        </div>

        <div v-if="footerItems.length > 0" class="flex flex-col gap-2">
          <SidebarButton
            v-for="item in footerItems"
            :key="item.id"
            :icon="item.icon"
            :to="item.to"
            :label="item.label"
          />
        </div>
      </aside>
    </template>
  </ResizableSidebar>
</template>

<style scoped>
.kepler-sidebar-project-link {
  border-radius: calc(var(--radius) * 1.4);
  corner-shape: var(--corner-shape);
}
</style>

// apps/delphi/ts/src/components/sideBar.tsx
import {
  Archive,
  Book,
  Calendar,
  Circle,
  Inbox,
  PanelLeftClose,
  PanelLeftOpen,
  Settings,
  Star,
} from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import SideBarButton from "@/components/SideBarButton";
import useTodoStore from "@/store/todos";
import { ProjectStatus } from "@/types/task";
import { ResizableSidebar, type SidebarConfig } from "@kosmos/ui-sidebar";

const STORAGE_KEY = "delphi-sidebar-config";

function loadConfig(): Partial<SidebarConfig> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as Partial<SidebarConfig>;
  } catch {
    // ignore
  }
  return {};
}

function saveConfig(config: SidebarConfig) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
}

function colorTagClass(colorTag?: string | null): string {
  switch (colorTag) {
    case "red": return "text-red-500";
    case "orange": return "text-orange-500";
    case "yellow": return "text-yellow-500";
    case "green": return "text-green-500";
    case "blue": return "text-blue-500";
    case "purple": return "text-purple-500";
    case "pink": return "text-pink-500";
    default: return "text-(--muted-foreground)";
  }
}

function SidebarExpandedContent({ toggle }: { toggle: () => void }) {
  const projects = useTodoStore((s) => s.projects);
  const activeProjects = projects
    .filter((p) => p.status === ProjectStatus.Active)
    .sort((a, b) => a.sortOrder - b.sortOrder);
  const location = useLocation();

  return (
    <aside className="flex min-h-0 h-full flex-col justify-between border-r border-r-(--border) bg-(--sidebar) p-2">
      {/* Drag region + collapse button */}
      <div className="flex items-center">
        <div
          style={{ WebkitAppRegion: "drag" } as React.CSSProperties}
          className="h-7 flex-1"
        />
        <button
          type="button"
          onClick={toggle}
          className="rounded-lg p-1.5 text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)"
          title="Скрыть сайдбар (⌘/)"
        >
          <PanelLeftClose size={16} />
        </button>
      </div>

      <div className="flex flex-1 flex-col overflow-y-auto">
        <SideBarButton icon={Inbox} to="/" label="Входящие" />
        <SideBarButton icon={Star} to="/today" label="Сегодня" />
        <SideBarButton icon={Calendar} to="/upcoming" label="Планы" />
        <SideBarButton icon={Book} to="/logbook" label="Журнал" />
        <SideBarButton icon={Archive} to="/trash" label="Корзина" />

        {activeProjects.length > 0 && (
          <>
            <div className="my-2 border-t border-(--border)" />
            <div className="px-3 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-wider text-(--muted-foreground)/60 select-none">
              Проекты
            </div>
            {activeProjects.map((project) => {
              const path = `/project/${project.id}`;
              const isActive = location.pathname === path;
              const base =
                "flex h-10 w-full cursor-pointer items-center gap-2.5 rounded-lg px-3 py-2 text-sm transition-colors";
              const activeClass = isActive
                ? "bg-(--accent) text-(--foreground) font-medium"
                : "text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)";
              return (
                <Link key={project.id} to={path} className={`${base} ${activeClass}`}>
                  <Circle size={10} className={`shrink-0 fill-current ${colorTagClass(project.colorTag)}`} />
                  <span className="truncate">{project.title}</span>
                </Link>
              );
            })}
          </>
        )}
      </div>

      <div className="flex flex-col gap-2">
        <SideBarButton icon={Settings} to="/settings" />
      </div>
    </aside>
  );
}

function SidebarCollapsedContent({ toggle }: { toggle: () => void }) {
  return (
    <aside className="flex min-h-0 flex-col items-center border-r border-r-(--border) bg-(--sidebar) py-2 px-1">
      <div
        style={{ WebkitAppRegion: "drag" } as React.CSSProperties}
        className="h-3 w-full shrink-0"
      />
      <button
        type="button"
        onClick={toggle}
        className="mb-2 rounded-lg p-2 text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)"
        title="Показать сайдбар (⌘/)"
      >
        <PanelLeftOpen size={18} />
      </button>
      <SideBarButton icon={Inbox} to="/" />
      <SideBarButton icon={Star} to="/today" />
      <SideBarButton icon={Calendar} to="/upcoming" />
      <SideBarButton icon={Book} to="/logbook" />
      <SideBarButton icon={Archive} to="/trash" />
      <div className="flex-1" />
      <SideBarButton icon={Settings} to="/settings" />
    </aside>
  );
}

export default function SideBar() {
  return (
    <ResizableSidebar
      defaultWidth={200}
      minWidth={160}
      maxWidth={320}
      collapseThreshold={60}
      toggleShortcut="meta+/"
      initialConfig={loadConfig()}
      onConfigChange={saveConfig}
      collapsedContent={(toggle) => <SidebarCollapsedContent toggle={toggle} />}
    >
      {(toggle) => <SidebarExpandedContent toggle={toggle} />}
    </ResizableSidebar>
  );
}
