// apps/delphi/ts/src/components/ModeToggle.tsx
import { Moon, Sun } from 'lucide-react';
import { useTheme } from '@/features/themeProvider';

export function ModeToggle() {
  const { theme, toggleTheme } = useTheme();
  return (
    <div className="inline-flex items-center gap-2 rounded-xl p-1 hover:bg-(--secondary)">
      <button
        type="button"
        onClick={toggleTheme}
        className="rounded-md p-3 text-sm"
      >
        {theme === 'dark' ? <Moon /> : <Sun />}
      </button>
      {/* <button onClick={() => setTheme('system')} className="text-xs underline">
        system
      </button> */}
    </div>
  );
}

// extensions/delphi/src/components/ModeToggle.vue
<script setup lang="ts">
import { Moon, Sun } from "@lucide/vue";
import { useTheme } from "@/composables/useTheme";

const { theme, toggleTheme } = useTheme();
</script>

<template>
  <div class="inline-flex items-center gap-2 rounded-xl p-1 hover:bg-(--secondary)">
    <button type="button" class="rounded-md p-3 text-sm" @click="toggleTheme">
      <Moon v-if="theme === 'dark'" />
      <Sun v-else />
    </button>
  </div>
</template>
