// apps/delphi/ts/src/components/sideBar.tsx
import {
  Archive,
  Book,
  Calendar,
  Circle,
  Inbox,
  PanelLeftClose,
  PanelLeftOpen,
  Settings,
  Star,
} from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import SideBarButton from "@/components/SideBarButton";
import useTodoStore from "@/store/todos";
import { ProjectStatus } from "@/types/task";
import { ResizableSidebar, type SidebarConfig } from "@kosmos/ui-sidebar";

const STORAGE_KEY = "delphi-sidebar-config";

function loadConfig(): Partial<SidebarConfig> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as Partial<SidebarConfig>;
  } catch {
    // ignore
  }
  return {};
}

function saveConfig(config: SidebarConfig) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
}

function colorTagClass(colorTag?: string | null): string {
  switch (colorTag) {
    case "red": return "text-red-500";
    case "orange": return "text-orange-500";
    case "yellow": return "text-yellow-500";
    case "green": return "text-green-500";
    case "blue": return "text-blue-500";
    case "purple": return "text-purple-500";
    case "pink": return "text-pink-500";
    default: return "text-(--muted-foreground)";
  }
}

function SidebarExpandedContent({ toggle }: { toggle: () => void }) {
  const projects = useTodoStore((s) => s.projects);
  const activeProjects = projects
    .filter((p) => p.status === ProjectStatus.Active)
    .sort((a, b) => a.sortOrder - b.sortOrder);
  const location = useLocation();

  return (
    <aside className="flex min-h-0 h-full flex-col justify-between border-r border-r-(--border) bg-(--sidebar) p-2">
      {/* Drag region + collapse button */}
      <div className="flex items-center">
        <div
          style={{ WebkitAppRegion: "drag" } as React.CSSProperties}
          className="h-7 flex-1"
        />
        <button
          type="button"
          onClick={toggle}
          className="rounded-lg p-1.5 text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)"
          title="Скрыть сайдбар (⌘/)"
        >
          <PanelLeftClose size={16} />
        </button>
      </div>

      <div className="flex flex-1 flex-col overflow-y-auto">
        <SideBarButton icon={Inbox} to="/" label="Входящие" />
        <SideBarButton icon={Star} to="/today" label="Сегодня" />
        <SideBarButton icon={Calendar} to="/upcoming" label="Планы" />
        <SideBarButton icon={Book} to="/logbook" label="Журнал" />
        <SideBarButton icon={Archive} to="/trash" label="Корзина" />

        {activeProjects.length > 0 && (
          <>
            <div className="my-2 border-t border-(--border)" />
            <div className="px-3 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-wider text-(--muted-foreground)/60 select-none">
              Проекты
            </div>
            {activeProjects.map((project) => {
              const path = `/project/${project.id}`;
              const isActive = location.pathname === path;
              const base =
                "flex h-10 w-full cursor-pointer items-center gap-2.5 rounded-lg px-3 py-2 text-sm transition-colors";
              const activeClass = isActive
                ? "bg-(--accent) text-(--foreground) font-medium"
                : "text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)";
              return (
                <Link key={project.id} to={path} className={`${base} ${activeClass}`}>
                  <Circle size={10} className={`shrink-0 fill-current ${colorTagClass(project.colorTag)}`} />
                  <span className="truncate">{project.title}</span>
                </Link>
              );
            })}
          </>
        )}
      </div>

      <div className="flex flex-col gap-2">
        <SideBarButton icon={Settings} to="/settings" />
      </div>
    </aside>
  );
}

function SidebarCollapsedContent({ toggle }: { toggle: () => void }) {
  return (
    <aside className="flex min-h-0 flex-col items-center border-r border-r-(--border) bg-(--sidebar) py-2 px-1">
      <div
        style={{ WebkitAppRegion: "drag" } as React.CSSProperties}
        className="h-3 w-full shrink-0"
      />
      <button
        type="button"
        onClick={toggle}
        className="mb-2 rounded-lg p-2 text-(--muted-foreground) hover:bg-(--secondary) hover:text-(--foreground)"
        title="Показать сайдбар (⌘/)"
      >
        <PanelLeftOpen size={18} />
      </button>
      <SideBarButton icon={Inbox} to="/" />
      <SideBarButton icon={Star} to="/today" />
      <SideBarButton icon={Calendar} to="/upcoming" />
      <SideBarButton icon={Book} to="/logbook" />
      <SideBarButton icon={Archive} to="/trash" />
      <div className="flex-1" />
      <SideBarButton icon={Settings} to="/settings" />
    </aside>
  );
}

export default function SideBar() {
  return (
    <ResizableSidebar
      defaultWidth={200}
      minWidth={160}
      maxWidth={320}
      collapseThreshold={60}
      toggleShortcut="meta+/"
      initialConfig={loadConfig()}
      onConfigChange={saveConfig}
      collapsedContent={(toggle) => <SidebarCollapsedContent toggle={toggle} />}
    >
      {(toggle) => <SidebarExpandedContent toggle={toggle} />}
    </ResizableSidebar>
  );
}

// extensions/delphi/src/components/SideBar.vue
<script setup lang="ts">
import { computed, shallowRef } from "vue";
import {
  Archive,
  ArrowLeft,
  Book,
  Globe,
  Inbox,
  Plus,
  Settings2,
  Star,
} from "lucide-vue-next";
import {
  Sidebar as KosmosSidebar,
  type SidebarConfig,
  type SidebarNavItem,
  type SidebarProjectGroup,
  type SidebarProjectItem,
} from "@kosmos/visuals";
import { useTodoStore } from "@/store/todos";
import { storeToRefs } from "pinia";
import { ProjectStatus } from "@/types/task";
import { setSidebarHidden } from "@/composables/useSidebarState";
import { useRoute, useRouter } from "vue-router";
import ProjectCreateDialog from "@/components/projects/ProjectCreateDialog.vue";
import type { ProjectCreatePayload } from "@/components/projects/ProjectCreateDialog.vue";

const STORAGE_KEY = "delphi-sidebar-config";

type SettingsTab = "general" | "spaces";

function loadConfig(): Partial<SidebarConfig> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) return JSON.parse(raw) as Partial<SidebarConfig>;
  } catch {
    // ignore
  }

  return {};
}

function saveConfig(config: SidebarConfig) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
  setSidebarHidden(config.hidden);
}

function colorTagClass(colorTag?: string | null): string {
  switch (colorTag) {
    case "red":
      return "bg-red-500";
    case "orange":
      return "bg-orange-500";
    case "yellow":
      return "bg-yellow-500";
    case "green":
      return "bg-green-500";
    case "blue":
      return "bg-blue-500";
    case "purple":
      return "bg-purple-500";
    case "pink":
      return "bg-pink-500";
    default:
      return "bg-(--muted-foreground)";
  }
}

const store = useTodoStore();
const { projects } = storeToRefs(store);
const route = useRoute();
const router = useRouter();
const initialConfig = loadConfig();
const isMac = navigator.platform.startsWith("Mac");
const projectCreateOpen = shallowRef(false);

const props = withDefaults(
  defineProps<{
    hidden?: boolean;
    showToggle?: boolean;
    reserveTopInset?: boolean;
  }>(),
  {
    hidden: undefined,
    showToggle: true,
    reserveTopInset: true,
  },
);

const isSettingsRoute = computed(() => route.path === "/settings");

const activeSettingsTab = computed<SettingsTab>(() => {
  const tabValue = Array.isArray(route.query.tab) ? route.query.tab[0] : route.query.tab;
  return tabValue === "spaces" ? "spaces" : "general";
});

const existingProjectTitles = computed(() => projects.value.map((project) => project.title));

const activeProjectItems = computed<SidebarProjectItem[]>(() =>
  projects.value
    .filter((project) => project.status === ProjectStatus.Active)
    .sort((left, right) => left.sortOrder - right.sortOrder)
    .map((project) => ({
      id: project.id,
      label: project.title,
      to: `/project/${project.id}`,
      active: route.path === `/project/${project.id}`,
      colorClass: colorTagClass(project.colorTag),
    })),
);

const projectGroups = computed<SidebarProjectGroup[]>(() => {
  if (isSettingsRoute.value) {
    return [];
  }

  return [
    {
      id: "projects",
      label: "Проекты",
      items: activeProjectItems.value,
      actionIcon: Plus,
      actionLabel: "Создать проект",
      actionTestId: "sidebar-create-project",
      onAction: () => {
        projectCreateOpen.value = true;
      },
    },
  ];
});

function setSettingsTab(tab: SettingsTab) {
  if (activeSettingsTab.value === tab) return;

  void router.replace({
    query: {
      ...route.query,
      tab,
    },
  });
}

function handleSettingsBack() {
  if (window.history.length > 1) {
    router.back();
    return;
  }

  void router.push("/");
}

function handleProjectCreate(payload: ProjectCreatePayload) {
  const project = store.addProject({
    title: payload.title,
    notes: payload.notes,
    colorTag: payload.colorTag,
    billable: payload.billable,
    price: payload.price,
  });

  projectCreateOpen.value = false;
  void router.push(`/project/${project.id}`);
}

const primaryItems = computed<SidebarNavItem[]>(() => {
  if (isSettingsRoute.value) {
    return [
      {
        id: "back",
        icon: ArrowLeft,
        label: "Назад",
        onClick: handleSettingsBack,
        testId: "settings-nav-back",
      },
      {
        id: "general",
        icon: Settings2,
        label: "Общие",
        active: activeSettingsTab.value === "general",
        onClick: () => setSettingsTab("general"),
        testId: "settings-nav-general",
      },
      {
        id: "spaces",
        icon: Globe,
        label: "Пространства",
        active: activeSettingsTab.value === "spaces",
        onClick: () => setSettingsTab("spaces"),
        testId: "settings-nav-spaces",
      },
    ];
  }

  return [
    { id: "inbox", icon: Inbox, to: "/", label: "Входящие" },
    { id: "today", icon: Star, to: "/today", label: "Сегодня" },
  ];
});

const footerItems = computed<SidebarNavItem[]>(() =>
  isSettingsRoute.value
    ? []
    : [
        { id: "logbook", icon: Book, to: "/logbook", label: "Журнал" },
        { id: "trash", icon: Archive, to: "/trash", label: "Корзина" },
      ],
);
</script>

<template>
  <KosmosSidebar
    :primary-items="primaryItems"
    :project-groups="projectGroups"
    :footer-items="footerItems"
    :is-mac="isMac"
    :default-width="200"
    :min-width="160"
    :max-width="320"
    toggle-shortcut="meta+b|ctrl+b"
    :initial-config="initialConfig"
    :hidden="props.hidden"
    :show-toggle="props.showToggle"
    :reserve-top-inset="props.reserveTopInset"
    @config-change="saveConfig"
  />

  <ProjectCreateDialog
    v-model:open="projectCreateOpen"
    :existing-titles="existingProjectTitles"
    @save="handleProjectCreate"
  />
</template>
