// apps/delphi/ts/src/components/ResizableSidebar.vue
<script setup lang="ts">
import { shallowRef, watch, onMounted, onUnmounted, computed } from "vue";
import "./sidebar.css";

export interface SidebarConfig {
  width: number;
  collapsed: boolean;
}

interface Props {
  defaultWidth?: number;
  minWidth?: number;
  maxWidth?: number;
  collapseThreshold?: number;
  toggleShortcut?: string;
  className?: string;
  initialConfig?: Partial<SidebarConfig>;
  dragRegion?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  defaultWidth: 200,
  minWidth: 160,
  maxWidth: 320,
  collapseThreshold: 60,
  toggleShortcut: undefined,
  className: undefined,
  initialConfig: undefined,
  dragRegion: false,
});

const emit = defineEmits<{
  configChange: [config: SidebarConfig];
}>();

const width = shallowRef(props.initialConfig?.width ?? props.defaultWidth);
const collapsed = shallowRef(props.initialConfig?.collapsed ?? false);
const isResizing = shallowRef(false);
const animating = shallowRef(false);

const resizeRaf = shallowRef<number | null>(null);
const animTimer = shallowRef<number | null>(null);
const isAnimatingRef = shallowRef(false);

// Keep a config ref in sync for use inside rAF callbacks
const configRef = shallowRef<SidebarConfig>({
  width: width.value,
  collapsed: collapsed.value,
});

watch([width, collapsed], () => {
  configRef.value = { width: width.value, collapsed: collapsed.value };
});

function notifyConfigChange(config: SidebarConfig) {
  emit("configChange", config);
}

function startAnimation() {
  if (animTimer.value) {
    window.clearTimeout(animTimer.value);
  }
  isAnimatingRef.value = true;
  animating.value = true;
  animTimer.value = window.setTimeout(() => {
    isAnimatingRef.value = false;
    animating.value = false;
    animTimer.value = null;
  }, 220);
}

function toggle() {
  startAnimation();
  const next = !collapsed.value;
  collapsed.value = next;
  notifyConfigChange({ width: width.value, collapsed: next });
}

// Keyboard shortcut
function handleKeydown(e: KeyboardEvent) {
  if (!props.toggleShortcut) return;

  const parts = props.toggleShortcut.toLowerCase().split("+");
  const key = parts[parts.length - 1];
  const needsMeta = parts.includes("meta");
  const needsCtrl = parts.includes("ctrl");
  const needsShift = parts.includes("shift");
  const needsAlt = parts.includes("alt");

  if (needsMeta && !e.metaKey) return;
  if (needsCtrl && !e.ctrlKey) return;
  if (needsShift && !e.shiftKey) return;
  if (needsAlt && !e.altKey) return;
  if (e.key !== key && e.key.toLowerCase() !== key) return;

  e.preventDefault();
  toggle();
}

// Resize handlers
function handleResizeStart(e: MouseEvent) {
  e.preventDefault();
  isResizing.value = true;
  document.body.classList.add("sidebar-resizing");
}

function handleResizeMove(e: MouseEvent) {
  if (isAnimatingRef.value) return;

  if (resizeRaf.value) {
    cancelAnimationFrame(resizeRaf.value);
  }

  resizeRaf.value = requestAnimationFrame(() => {
    if (isAnimatingRef.value) return;

    const newWidth = e.clientX;

    if (newWidth <= props.collapseThreshold) {
      if (!configRef.value.collapsed) {
        startAnimation();
        collapsed.value = true;
        configRef.value = { ...configRef.value, collapsed: true };
      }
      return;
    }

    if (configRef.value.collapsed) {
      startAnimation();
      collapsed.value = false;
      width.value = props.minWidth;
      configRef.value = { width: props.minWidth, collapsed: false };
      return;
    }

    const clamped = Math.max(
      props.minWidth,
      Math.min(props.maxWidth, newWidth),
    );
    width.value = clamped;
    configRef.value = { ...configRef.value, width: clamped };
  });
}

function handleResizeEnd() {
  if (resizeRaf.value) {
    cancelAnimationFrame(resizeRaf.value);
    resizeRaf.value = null;
  }
  isResizing.value = false;
  document.body.classList.remove("sidebar-resizing");
  notifyConfigChange(configRef.value);
}

// Attach/detach global mouse listeners during resize
watch(isResizing, (resizing) => {
  if (resizing) {
    window.addEventListener("mousemove", handleResizeMove);
    window.addEventListener("mouseup", handleResizeEnd);
  } else {
    window.removeEventListener("mousemove", handleResizeMove);
    window.removeEventListener("mouseup", handleResizeEnd);
  }
});

onMounted(() => {
  window.addEventListener("keydown", handleKeydown);
});

onUnmounted(() => {
  window.removeEventListener("keydown", handleKeydown);
  window.removeEventListener("mousemove", handleResizeMove);
  window.removeEventListener("mouseup", handleResizeEnd);
  if (animTimer.value) window.clearTimeout(animTimer.value);
  if (resizeRaf.value) cancelAnimationFrame(resizeRaf.value);
  document.body.classList.remove("sidebar-resizing");
});

const wrapperClasses = computed(() =>
  [
    "kosmos-sidebar-wrapper",
    collapsed.value ? "collapsed" : "",
    animating.value ? "animating" : "",
    isResizing.value ? "is-resizing" : "",
    props.className ?? "",
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <!-- Collapsed with collapsed slot -->
  <template v-if="collapsed && $slots.collapsed">
    <slot name="collapsed" :toggle="toggle" />
  </template>

  <!-- Collapsed without collapsed slot -->
  <div
    v-else-if="collapsed"
    :class="wrapperClasses"
    :style="{ width: '0px' }"
  />

  <!-- Expanded -->
  <div v-else :class="wrapperClasses" :style="{ width: `${width}px` }">
    <div
      v-if="dragRegion"
      :style="{ WebkitAppRegion: 'drag' } as any"
      class="kosmos-sidebar-drag-region"
    />
    <div
      class="kosmos-sidebar-content"
      :style="{ width: `${width}px`, minWidth: `${width}px` }"
    >
      <slot :toggle="toggle" />
    </div>
    <div class="kosmos-sidebar-resize-handle" @mousedown="handleResizeStart">
      <div class="kosmos-resize-handle-line" />
    </div>
  </div>
</template>

// packages/ui/sidebar/ResizableSidebar.tsx
import { useState, useEffect, useCallback, useRef, type ReactNode, type MouseEvent as ReactMouseEvent } from 'react';
import './sidebar.css';

export interface SidebarConfig {
  width: number;
  collapsed: boolean;
}

export interface ResizableSidebarProps {
  /** Sidebar content when expanded — render prop receiving toggle */
  children: (toggle: () => void) => ReactNode;
  /** Default width in pixels */
  defaultWidth?: number;
  /** Minimum width before collapse threshold */
  minWidth?: number;
  /** Maximum width */
  maxWidth?: number;
  /** Width below which sidebar auto-collapses during drag */
  collapseThreshold?: number;
  /** Keyboard shortcut to toggle (e.g., "meta+/") */
  toggleShortcut?: string;
  /** CSS class for the sidebar wrapper */
  className?: string;
  /** Callback when config changes (for persistence) */
  onConfigChange?: (config: SidebarConfig) => void;
  /** Initial config (loaded from persistence) */
  initialConfig?: Partial<SidebarConfig>;
  /** Content to show when collapsed — render prop receiving toggle */
  collapsedContent?: (toggle: () => void) => ReactNode;
  /** Drag region for Electron titlebar */
  dragRegion?: boolean;
}

export function ResizableSidebar({
  children,
  defaultWidth = 200,
  minWidth = 160,
  maxWidth = 320,
  collapseThreshold = 60,
  toggleShortcut,
  className,
  onConfigChange,
  initialConfig,
  collapsedContent,
  dragRegion = false,
}: ResizableSidebarProps) {
  const [width, setWidth] = useState(initialConfig?.width ?? defaultWidth);
  const [collapsed, setCollapsed] = useState(initialConfig?.collapsed ?? false);
  const [isResizing, setIsResizing] = useState(false);
  const [animating, setAnimating] = useState(false);

  const resizeRef = useRef<number | null>(null);
  const animTimerRef = useRef<number | null>(null);
  const isAnimatingRef = useRef(false);
  const configRef = useRef<SidebarConfig>({ width, collapsed });

  useEffect(() => {
    configRef.current = { width, collapsed };
  }, [width, collapsed]);

  const notifyConfigChange = useCallback((config: SidebarConfig) => {
    onConfigChange?.(config);
  }, [onConfigChange]);

  const startAnimation = useCallback(() => {
    if (animTimerRef.current) {
      window.clearTimeout(animTimerRef.current);
    }
    isAnimatingRef.current = true;
    setAnimating(true);
    animTimerRef.current = window.setTimeout(() => {
      isAnimatingRef.current = false;
      setAnimating(false);
      animTimerRef.current = null;
    }, 220);
  }, []);

  const toggle = useCallback(() => {
    startAnimation();
    setCollapsed((prev) => {
      const next = !prev;
      const config = { width: configRef.current.width, collapsed: next };
      notifyConfigChange(config);
      return next;
    });
  }, [startAnimation, notifyConfigChange]);

  // Keyboard shortcut
  useEffect(() => {
    if (!toggleShortcut) return;

    const parts = toggleShortcut.toLowerCase().split('+');
    const key = parts[parts.length - 1];
    const needsMeta = parts.includes('meta');
    const needsCtrl = parts.includes('ctrl');
    const needsShift = parts.includes('shift');
    const needsAlt = parts.includes('alt');

    const handler = (e: KeyboardEvent) => {
      if (needsMeta && !e.metaKey) return;
      if (needsCtrl && !e.ctrlKey) return;
      if (needsShift && !e.shiftKey) return;
      if (needsAlt && !e.altKey) return;
      if (e.key !== key && e.key.toLowerCase() !== key) return;

      e.preventDefault();
      toggle();
    };

    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [toggleShortcut, toggle]);

  // Resize mouse handlers
  const handleResizeStart = useCallback((e: ReactMouseEvent) => {
    e.preventDefault();
    setIsResizing(true);
    document.body.classList.add('sidebar-resizing');
  }, []);

  const handleResizeMove = useCallback((e: MouseEvent) => {
    if (isAnimatingRef.current) return;

    if (resizeRef.current) {
      cancelAnimationFrame(resizeRef.current);
    }

    resizeRef.current = requestAnimationFrame(() => {
      if (isAnimatingRef.current) return;

      const newWidth = e.clientX;

      if (newWidth <= collapseThreshold) {
        if (!configRef.current.collapsed) {
          startAnimation();
          setCollapsed(true);
          configRef.current = { ...configRef.current, collapsed: true };
        }
        return;
      }

      if (configRef.current.collapsed) {
        startAnimation();
        setCollapsed(false);
        setWidth(minWidth);
        configRef.current = { width: minWidth, collapsed: false };
        return;
      }

      const clamped = Math.max(minWidth, Math.min(maxWidth, newWidth));
      setWidth(clamped);
      configRef.current = { ...configRef.current, width: clamped };
    });
  }, [collapseThreshold, minWidth, maxWidth, startAnimation]);

  const handleResizeEnd = useCallback(() => {
    if (resizeRef.current) {
      cancelAnimationFrame(resizeRef.current);
      resizeRef.current = null;
    }
    setIsResizing(false);
    document.body.classList.remove('sidebar-resizing');
    notifyConfigChange(configRef.current);
  }, [notifyConfigChange]);

  // Attach/detach global mouse listeners during resize
  useEffect(() => {
    if (!isResizing) return;

    window.addEventListener('mousemove', handleResizeMove);
    window.addEventListener('mouseup', handleResizeEnd);

    return () => {
      window.removeEventListener('mousemove', handleResizeMove);
      window.removeEventListener('mouseup', handleResizeEnd);
    };
  }, [isResizing, handleResizeMove, handleResizeEnd]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (animTimerRef.current) window.clearTimeout(animTimerRef.current);
      if (resizeRef.current) cancelAnimationFrame(resizeRef.current);
      document.body.classList.remove('sidebar-resizing');
    };
  }, []);

  // When collapsed and collapsed content is provided, render it directly
  if (collapsed && collapsedContent) {
    return <>{collapsedContent(toggle)}</>;
  }

  // When collapsed without collapsed content, render zero-width wrapper
  if (collapsed) {
    return (
      <div
        className={[
          'kosmos-sidebar-wrapper',
          'collapsed',
          animating ? 'animating' : '',
          className ?? '',
        ].filter(Boolean).join(' ')}
        style={{ width: 0 }}
      />
    );
  }

  const wrapperClasses = [
    'kosmos-sidebar-wrapper',
    animating ? 'animating' : '',
    isResizing ? 'is-resizing' : '',
    className ?? '',
  ].filter(Boolean).join(' ');

  return (
    <div className={wrapperClasses} style={{ width }}>
      {dragRegion && (
        <div
          style={{ WebkitAppRegion: 'drag' } as React.CSSProperties}
          className="kosmos-sidebar-drag-region"
        />
      )}
      <div className="kosmos-sidebar-content" style={{ width, minWidth: width }}>
        {children(toggle)}
      </div>
      <div className="kosmos-sidebar-resize-handle" onMouseDown={handleResizeStart}>
        <div className="kosmos-resize-handle-line" />
      </div>
    </div>
  );
}
